Repository MbinOrg/mbin, pull requests merged in 2023-12, with the labels that each got.

#321 Use the official PHPUnit Bridge recipe again for phpunit v10
  bin/phpunit
  phpunit.xml.dist
  symfony.lock
Labels: testing

#322 Add an edit my profile button to your own user profile pages
  templates/components/user_actions.html.twig
  translations/messages.en.yaml
Labels: frontend

#324 Update symfony packages
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/routes/security.yaml
  symfony.lock
Labels: dependencies, backend

#325 Add missing deleted by translations
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/entry_cross.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  translations/messages.en.yaml
Labels: translation

#331 Unable to ban admin
  src/Exception/UserCannotBeBanned.php
  src/Service/MagazineManager.php
  src/Service/UserManager.php
  src/Twig/Runtime/UserExtensionRuntime.php
Labels: enhancement, backend

#300 do not automatically show media previews of nsfw posts
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
Labels: frontend

#336 Introducing a Project Info service (updates useragent version as well)
  src/Factory/ActivityPub/NodeInfoFactory.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ProjectInfoService.php
Labels: enhancement, activitypub, backend

#333 using blurhash for entry thumbnail blurred background
  assets/styles/components/_comment.scss
  assets/styles/components/_entry.scss
  src/Twig/Components/BlurhashImageComponent.php
  templates/components/blurhash_image.html.twig
  templates/components/entry.html.twig
Labels: frontend

#337 Add a small margin between top level entry comments
  assets/styles/components/_comment.scss
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/entry/_list.html.twig
  templates/entry/comment/_list.html.twig
  templates/entry/single.html.twig
  templates/post/_list.html.twig
  templates/post/comment/_list.html.twig
  templates/post/single.html.twig
Labels: frontend

#340 Add current sort and time options to navbar links
  src/Twig/Runtime/NavbarExtensionRuntime.php
Labels: enhancement

#339 Hide NSFW posts on user overview page when logged out or hide NSFW enabled
  src/Command/Update/UserLastActiveUpdateCommand.php
  src/Controller/ActivityPub/User/UserOutboxController.php
  src/Controller/User/UserFrontController.php
  src/Repository/UserRepository.php
Labels: backend

#343 fix comment sort order being used for navbar sort
  src/Twig/Runtime/NavbarExtensionRuntime.php
Labels: bug

#342 using blurhash for obscuring sensitive image
  assets/styles/app.scss
  assets/styles/components/_comment.scss
  assets/styles/components/_entry.scss
  assets/styles/components/_figure_image.scss
  assets/styles/components/_post.scss
  src/Twig/Components/BlurhashImageComponent.php
  templates/components/_figure_entry.html.twig
  templates/components/_figure_image.html.twig
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  translations/messages.en.yaml
Labels: enhancement, please review

#353 Add captcha to contact form
  src/Form/ContactType.php
  templates/page/contact.html.twig
Labels: enhancement

#257 remove system-ui font due to display issues
  assets/styles/_variables.scss
  assets/styles/components/_entry.scss
  assets/styles/components/_header.scss
  assets/styles/components/_sidebar.scss
  assets/styles/emails.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-light.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
  assets/styles/themes/_kbin.scss
  assets/styles/themes/_tokyo-night.scss
Labels: frontend

#359 Fix 2 errors when announcing anything
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
  src/Service/ActivityPub/Wrapper/AnnounceWrapper.php
Labels: bug, activitypub, backend

#360 Update time filter display
  assets/styles/layout/_options.scss
  src/Twig/Extension/ContextExtension.php
  src/Twig/Runtime/ContextExtensionRuntime.php
  templates/entry/_options.html.twig
  templates/post/_options.html.twig
  translations/messages.en.yaml
Labels: frontend

#375 Update footer language selector to include Bulgarian, README update
  README.md
  templates/layout/_footer.html.twig
Labels: documentation, frontend

#376 remove admin submenu when viewing reports as global mod
  templates/admin/pages.html.twig
  templates/admin/reports.html.twig
Labels: low priority

#380 Add user verify command to activate/deactivate user via php bin/console
  src/Command/VerifyCommand.php
Labels: backend

#381 Fix 500 on parsed unresolved remote mags (might be specific to Flipboard)
  src/Markdown/CommonMark/CommunityLinkParser.php
Labels: bug, please review, backend

#378 increase image store exception logging to error
  src/Repository/ImageRepository.php
Labels: backend

#382 Update console commands to use mbin naming convention
  FAQ.md
  docs/admin_guide.md
  docs/docker_deployment_guide.md
  src/Command/ActorUpdateCommand.php
  src/Command/AdminCommand.php
  src/Command/ApImportObject.php
  src/Command/AwesomeBot/AwesomeBotEntries.php
  src/Command/AwesomeBot/AwesomeBotFixtures.php
  src/Command/AwesomeBot/AwesomeBotMagazine.php
  src/Command/ImageCacheCommand.php
  src/Command/MagazineUnsubCommand.php
  src/Command/MoveEntriesByTagCommand.php
  src/Command/MovePostsByTagCommand.php
  src/Command/PostMagazinesUpdateCommand.php
  src/Command/RemoveDuplicatesCommand.php
  src/Command/SubMagazineCommand.php
  src/Command/Update/ApKeysUpdateCommand.php
  src/Command/Update/ImageBlurhashUpdateCommand.php
  src/Command/Update/LocalMagazineApProfile.php
  src/Command/Update/NoteVisibilityUpdateCommand.php
  src/Command/Update/PostCommentRootUpdateCommand.php
  src/Command/Update/RemoveMagazineNameFromTagsCommand.php
  src/Command/Update/SlugUpdateCommand.php
  src/Command/Update/TagsToJsonbUpdateCommand.php
  src/Command/Update/TagsUpdateCommand.php
  src/Command/Update/UserLastActiveUpdateCommand.php
  src/Command/UserCommand.php
  src/Command/UserUnsubCommand.php
  src/Command/VerifyCommand.php
  tests/Functional/Command/AdminCommandTest.php
  tests/Functional/Command/UserCommandTest.php
Labels: documentation, backend

#377 fix malformed external media link label that contain newline
  src/Service/ActivityPub/ApObjectExtractor.php
Labels: activitypub, backend

#355 markdown details/spoilers block extension
  assets/styles/_variables.scss
  assets/styles/layout/_layout.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-light.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
  assets/styles/themes/_kbin.scss
  assets/styles/themes/_tokyo-night.scss
  src/Markdown/CommonMark/DetailsBlockParser.php
  src/Markdown/CommonMark/DetailsBlockRenderer.php
  src/Markdown/CommonMark/DetailsBlockStartParser.php
  src/Markdown/CommonMark/Node/DetailsBlock.php
  src/Markdown/MarkdownExtension.php
  templates/base.html.twig
  templates/components/_details_label.css.twig
  translations/messages.en.yaml
Labels: enhancement

#379 adjust logging for docker setups
  config/packages/monolog.yaml
  docker/Dockerfile
  docker/compose.yml
  docs/docker_deployment_guide.md
Labels: docker

#383 fix js error when clicking home button on mobile sidebar
  templates/layout/_sidebar.html.twig
Labels: low priority

#386 Update admin docs for manual user activation
  docs/admin_guide.md
  docs/docker_deployment_guide.md
Labels: documentation

#387 Rename "bot" user agent string and route to "agent"
  config/kbin_routes/landing.yaml
  config/packages/framework.yaml
  src/Controller/AgentController.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ProjectInfoService.php
  templates/page/agent.html.twig
  translations/messages.en.yaml
Labels: backend
