Repository MbinOrg/mbin, pull requests merged in 2023-10, with the labels that each got.

#17 Update oauth2_guide.md
  docs/oauth2_guide.md
Labels: Please review

#55 Remove Nginx referrer policy setting from admin guide
  docs/admin_guide.md
Labels: documentation

#57 docker guide - remove duplicate system requirements section
  docs/docker_deployment_guide.md
Labels: documentation

#51 new/alternate mbin opengraph image
  assets/images/sources/mbin-notext.svg
  assets/images/sources/mbin-og.svg
  assets/images/sources/mbin-text.svg
  docs/images/mbin.png
  public/mbin-og.png
  public/mbin_logo.png
  public/mbin_logo.svg
  public/mbin_logo_white.png
Labels: help wanted

#65 sidebar - remove instances placeholder
  templates/layout/_sidebar.html.twig
Labels: needs feedback

#72 Supporting different actor types as User + Improved actor checking
  assets/styles/components/_user.scss
  composer.lock
  config/services.yaml
  migrations/Version20231019190634.php
  phpunit.xml.dist
  src/Entity/User.php
  src/Factory/ActivityPub/InstanceFactory.php
  src/Factory/ActivityPub/PersonFactory.php
  src/Factory/UserFactory.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPubManager.php
  src/Service/UserManager.php
  src/Service/VoteManager.php
  symfony.lock
  templates/components/user_box.html.twig
  tests/bootstrap.php
Labels: activitypub

#82 List our unique features
  README.md
Labels: documentation

#81 handle alt text overflow on broken avatar images
  assets/styles/components/_comment.scss
  assets/styles/components/_user.scss
  templates/components/user_avatar.html.twig
  templates/components/user_inline.html.twig
  templates/entry/_info.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/post/_info.html.twig
  templates/user/_info.html.twig
  templates/user/_list.html.twig
Labels: enhancement, frontend

#84 Update Dockerfile v2 to use lts-alpine image for yarn builder
  docker/v2/Dockerfile
Labels: docker

#87 Adjust User class constructor to support type field during object instantiation
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Service/UserManager.php
  tests/FactoryTrait.php
Labels: backend

#92 Add PCNTL PHP extension to Docker environment
  docker/v2/Dockerfile
Labels: docker

#79 some S3 instruction for media storage, and fix media storage filesystem abstraction along the way
  config/packages/liip_imagine.yaml
  config/packages/oneup_flysystem.yaml
  config/services.yaml
  docs/admin_guide.md
Labels: enhancement, please review

#94 Just very small doc changes
  FAQ.md
  docs/admin_guide.md
Labels: documentation

#90 Improve error warning log pollution (Part 1)
  src/Controller/SearchController.php
  src/MessageHandler/ActivityPub/Inbox/FollowHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPub/Question.php
  src/Service/ActivityPub/SignatureValidator.php
  src/Service/SearchManager.php
Labels: enhancement, backend

#97 Update PWA manifest to reflect Mbin branding
  public/assets/icons/mbin-shortcut-base-file.psd
  public/assets/icons/mbin-shortcut-magazine.png
  public/assets/icons/mbin-shortcut-microblog.png
  public/assets/icons/mbin-shortcut-people.png
  public/assets/icons/mbin-shortcut-settings.png
  public/assets/screenshots/screen.png
  public/manifest.json
Labels: frontend

#96 Improve error warning log pollution (Part 2)
  README.md
  composer.lock
  config/packages/doctrine.yaml
  config/packages/liip_imagine.yaml
  config/packages/messenger.yaml
  config/packages/prod/doctrine.yaml
  config/packages/test/doctrine.yaml
  config/packages/test/validator.yaml
  config/packages/validator.yaml
  src/Entity/Client.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/Service/ActivityPub/Page.php
  symfony.lock
Labels: enhancement, backend

#99 Check if ENABLE_ACL is set before variable access
  docker/docker-entrypoint
Labels: docker

#101 Update FAQ.md
  FAQ.md
Labels: documentation

#75 Cardano (Wallet) removal
  config/kbin_routes/cardano.yaml
  config/kbin_routes/entry.yaml
  config/services.yaml
  migrations/Version20231019023030.php
  src/ArgumentValueResolver/CardanoTxInitResolver.php
  src/ArgumentValueResolver/CardanoTxResolver.php
  src/Cardano/CardanoExplorer.php
  src/Cardano/CardanoWallet.php
  src/Cardano/CardanoWalletTransactions.php
  src/Cardano/Model/CardanoTransaction.php
  src/Command/AwesomeBot/AwesomeBotFixtures.php
  src/Command/CardanoWalletObserverCommand.php
  src/Controller/Cardano/CardanoController.php
  src/Controller/Cardano/CardanoTransactionController.php
  src/Controller/Cardano/CardanoTransactionFeeController.php
  src/Controller/Cardano/CardanoWalletCreateController.php
  src/Controller/Cardano/CardanoWalletDetachController.php
  src/Controller/Cardano/CardanoWalletMnemonicController.php
  src/Controller/Entry/EntryCardanoTxInitController.php
  src/Controller/Entry/EntryTipController.php
  src/Controller/User/Profile/UserTipController.php
  src/DTO/CardanoMnemonicDto.php
  src/DTO/CardanoTransactionDto.php
  src/DTO/CardanoWalletAddressDto.php
  src/Entity/CardanoTx.php
  src/Entity/CardanoTxInit.php
  src/Entity/Entry.php
  src/Entity/EntryCardanoTx.php
  src/Entity/EntryCardanoTxInit.php
  src/Entity/User.php
  src/Form/CardanoMnemonicType.php
  src/Form/CardanoTransactionType.php
  src/Form/CardanoWalletAddressType.php
  src/Message/Cardano/SubjectTransactionsRefreshMessage.php
  src/MessageHandler/Cardano/SubjectTransactionsRefreshHandler.php
  src/Repository/CardanoTxInitRepository.php
  src/Repository/CardanoTxRepository.php
  src/Service/CardanoManager.php
  src/Service/UserManager.php
Labels: enhancement, help wanted, please review

#106 fix type mismatch when querying AP user follower/following list
  src/Controller/ActivityPub/User/UserFollowersController.php
Labels: bug, backend

#107 enable auto rotate filter when making thumbnail
  config/packages/liip_imagine.yaml
  docker/Dockerfile
Labels: enhancement, frontend

#109 Prevent failed preview loads from redirecting (#303)
  assets/controllers/preview_controller.js
Labels: enhancement, frontend

#111 Update docs (readme & FAQ)
  FAQ.md
  README.md
Labels: documentation

#112 Change from info to debug level
  src/Controller/ActivityPub/Magazine/MagazineInboxController.php
  src/Controller/ActivityPub/SharedInboxController.php
  src/Controller/ActivityPub/User/UserInboxController.php
  src/Controller/Api/Post/PostsRetrieveApi.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/SignatureValidator.php
Labels: enhancement, backend

#113 adding display and overflow properties to images with alt text
  assets/styles/app.scss
  assets/styles/components/_main.scss
  assets/styles/components/_user.scss
  assets/styles/layout/_images.scss
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/user_avatar.html.twig
  templates/components/user_box.html.twig
  templates/components/user_image_component.html.twig
  templates/components/user_inline.html.twig
  templates/entry/_info.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/post/_info.html.twig
  templates/user/_info.html.twig
  templates/user/_list.html.twig
Labels: enhancement, frontend

#100 Improve error warning log pollution + composer recipes (Part 3)
  assets/app.js
  assets/bootstrap.js
  config/packages/dev/monolog.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/monolog.yaml
  config/packages/oneup_flysystem.yaml
  config/packages/prod/deprecations.yaml
  config/packages/prod/monolog.yaml
  config/packages/security.yaml
  config/packages/test/monolog.yaml
  config/packages/translation.yaml
  symfony.lock
Labels: enhancement, backend

#115 Improve bare metal docs, composer file and dot config files
  .env.example
  .env.example_docker
  docker/compose.yml
  docs/admin_guide.md
Labels: documentation, backend, docker

#116 Improve local dev setup
  README.md
Labels: documentation

#114 Update admin_guide.md
  docs/admin_guide.md
Labels: documentation

#83 Add Psalm code security scanning
  .github/workflows/psalm.yml
Labels: security

#119 Futher improve admin guides
  docs/admin_guide.md
  docs/docker_deployment_guide.md
Labels: documentation

#122 Improve docker-entrypoint for prod & dev
  docker/docker-entrypoint
Labels: backend, docker

#123 Updating packages & recipes
  .editorconfig
  composer.lock
  config/packages/dev/rate_limiter.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/framework.yaml
  config/packages/league_oauth2_server.yaml
  config/packages/liip_imagine.yaml
  config/packages/lock.yaml
  config/packages/mailer.yaml
  config/packages/mercure.yaml
  config/packages/messenger.yaml
  config/packages/meteo_concept_h_captcha.yaml
  config/packages/monolog.yaml
  config/packages/nelmio_cors.yaml
  config/packages/nyholm_psr7.yaml
  config/packages/prod/webpack_encore.yaml
  config/packages/security.yaml
  config/packages/test/validator.yaml
  config/packages/test/web_profiler.yaml
  config/packages/twig.yaml
  config/packages/validator.yaml
  config/packages/web_profiler.yaml
  config/routes/dev/framework.yaml
  config/routes/dev/web_profiler.yaml
  config/routes/web_profiler.yaml
  config/services.yaml
  src/Kernel.php
  symfony.lock
Labels: dependencies, backend

#126 Weblate typo
  README.md
Labels: documentation

#128 Fix composer dev mode bug in docker-entrypoint
  docker/Dockerfile
  docker/docker-entrypoint
Labels: bug, docker

#130 Explain increasing verbosity level of monolog
  README.md
  config/packages/monolog.yaml
Labels: documentation

#129 Update FAQ due to enabling log rotation
  FAQ.md
Labels: documentation

#132 Improved docker setup & guide
  .dockerignore
  docker/compose.prod.yml
  docs/docker_deployment_guide.md
Labels: documentation, docker

#133 Ensure doctrine migration (and ACL set if enabled) only happens once when php-fpm is started
  docker/docker-entrypoint
Labels: bug, docker

#134 Include bundles directory to copy over necessary files for API in docker environment
  docker/Dockerfile
Labels: bug, docker

#137 user box template - fix losing cover class
  templates/components/user_box.html.twig
Labels: frontend

#136 Add CSRF token to logout
  config/packages/security.yaml
  templates/layout/_header.html.twig
  templates/user/2fa.html.twig
Labels: backend, security

#139 Subscription sidebar
  assets/styles/app.scss
  assets/styles/components/_sidebar-subscriptions.scss
  assets/styles/layout/_layout.scss
  src/Controller/User/ThemeSettingsController.php
  src/Twig/Components/SidebarSubscriptionComponent.php
  templates/base.html.twig
  templates/layout/_options_appearance.html.twig
  templates/layout/_sidebar.html.twig
  templates/layout/sidebar_subscriptions.html.twig
  translations/messages.en.yaml
Labels: enhancement, please review, frontend, backend

#140 Improve error warning log pollution + dev setup + composer update (part 5)
  CONTRIBUTING.md
  README.md
  assets/controllers/notifications_controller.js
  assets/utils/event-source.js
  composer.lock
  config/packages/monolog.yaml
  config/packages/security.yaml
  docs/docker_deployment_guide.md
  src/Security/OAuth/ClientCredentialsGrant.php
  src/Security/UserChecker.php
  src/Validator/Unique.php
  tests/WebTestCase.php
Labels: documentation, enhancement, backend

#149 Ask for instance domain/url in GitHub issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#150 Remove height 100% from label class in settings
  assets/styles/components/_settings_row.scss
Labels: frontend

#147 Ran compose recipes + Move to NPM + port 8008 (Part 6)
  .github/workflows/action.yaml
  .gitignore
  README.md
  assets/app.js
  bin/post-upgrade
  ci/Dockerfile
  clover.xml
  config/packages/assets.yaml
  config/packages/doctrine.yaml
  config/packages/prod/doctrine.yaml
  config/packages/prod/webpack_encore.yaml
  config/packages/test/doctrine.yaml
  config/packages/test/webpack_encore.yaml
  config/packages/webpack_encore.yaml
  docker/Dockerfile
  docker/compose.yml
  docs/admin_guide.md
  docs/docker_deployment_guide.md
  package-lock.json
  package.json
  symfony.lock
  yarn.lock
Labels: documentation, enhancement, dependencies, backend, docker

#156 Handle errrors and successes on forms
  .editorconfig
  config/kbin_routes/user.yaml
  src/Controller/ContactController.php
  src/Controller/Entry/Comment/EntryCommentCreateController.php
  src/Controller/Entry/Comment/EntryCommentEditController.php
  src/Controller/Entry/EntryCreateController.php
  src/Controller/Entry/EntryEditController.php
  src/Controller/Magazine/MagazineCreateController.php
  src/Controller/Magazine/Panel/MagazineEditController.php
  src/Controller/Magazine/Panel/MagazineThemeController.php
  src/Controller/Post/Comment/PostCommentCreateController.php
  src/Controller/Post/Comment/PostCommentEditController.php
  src/Controller/Post/PostCreateController.php
  src/Controller/Post/PostEditController.php
  src/Controller/User/Profile/User2FAController.php
  src/Controller/User/Profile/UserEditController.php
  src/Controller/User/Profile/UserSettingController.php
  src/Form/EventListener/AvatarListener.php
  src/Form/EventListener/ImageListener.php
  src/Repository/ImageRepository.php
  src/Service/ImageManager.php
  templates/layout/_flash.html.twig
  templates/magazine/panel/general.html.twig
  templates/magazine/panel/theme.html.twig
  templates/user/settings/email.html.twig
  templates/user/settings/general.html.twig
  templates/user/settings/password.html.twig
  templates/user/settings/profile.html.twig
  translations/messages.en.yaml
Labels: documentation, enhancement, frontend

#160 remove autofocus from 2fa setup page
  src/Form/UserTwoFactorType.php
Labels: low priority

#164 Change QR path without using a file extenstion
  config/kbin_routes/user.yaml
  src/Controller/User/Profile/User2FAController.php
Labels: bug, backend

#163 Revert "Limitation of random sidebar content" Part 2
  src/Repository/MagazineRepository.php
Labels: backend

#165 Introduces docker build and publish job
  .editorconfig
  .github/workflows/action.yaml
  .github/workflows/psalm.yml
Labels: enhancement, please review, docker

#167 Fix Docker push
  .github/workflows/action.yaml
Labels: bug

#121 adding sidebar setting for controlling container width
  assets/styles/components/_sidebar.scss
  assets/styles/layout/_layout.scss
  src/Controller/User/ThemeSettingsController.php
  src/Twig/Components/SettingsRowEnumComponent.php
  templates/base.html.twig
  templates/components/_settings_row_enum.html.twig
  templates/layout/_options_appearance.html.twig
  translations/messages.en.yaml
Labels: needs feedback, frontend

#168 Enable avatars by default
  templates/components/entry.html.twig
  templates/layout/_options_appearance.html.twig
Labels: frontend

#157 comment reply position - translate top label text
  templates/layout/_options_appearance.html.twig
  translations/messages.en.yaml
Labels: bug

#153 Explain Nginx setup for Docker (and bare metal for www)
  docs/admin_guide.md
  docs/docker_deployment_guide.md
Labels: documentation, please review

#178 Improve readme
  README.md
Labels: documentation

#146 fix inline link preview basically imploded when trying open preview
  assets/controllers/preview_controller.js
  assets/styles/components/_entry.scss
  assets/styles/components/_preview.scss
  src/Controller/AjaxController.php
  src/Markdown/CommonMark/EmbedElement.php
  templates/components/entry.html.twig
Labels: please review, frontend

#176 fix page width not affecting header and footer
  assets/styles/layout/_layout.scss
  templates/layout/_footer.html.twig
  templates/layout/_header.html.twig
Labels: bug, frontend

#183 Prepare for tombstone support
  src/Service/ActivityPub/ApHttpClient.php
Labels: enhancement, activitypub, backend

#182 Become a contributor
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#184 Fix undefined $entity variable message and more
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
Labels: enhancement, activitypub, backend
