Repository MbinOrg/mbin, pull requests merged in 2023-11, with the labels that each got.

#180 Update FAQ.md
  FAQ.md
Labels: documentation

#187 Remove the translations to lower.
  templates/admin/_options.html.twig
  templates/admin/users.html.twig
  templates/awards/_options.html.twig
  templates/components/boost.html.twig
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/favourite.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/components/voters_inline.html.twig
  templates/entry/_create_options.html.twig
  templates/entry/_options.html.twig
  templates/entry/_options_activity.html.twig
  templates/entry/comment/_moderate_panel.html.twig
  templates/entry/comment/_options.html.twig
  templates/entry/comment/_options_activity.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/magazine/_options.html.twig
  templates/magazine/panel/_options.html.twig
  templates/post/_moderate_panel.html.twig
  templates/post/_options.html.twig
  templates/post/_options_activity.html.twig
  templates/post/comment/_moderate_panel.html.twig
  templates/post/comment/_options.html.twig
  templates/post/comment/_options_activity.html.twig
  templates/stats/_filters.html.twig
  templates/stats/_options.html.twig
  templates/user/_options.html.twig
  templates/user/settings/_options.html.twig
Labels: enhancement, frontend

#196 minor contributing doc change
  CONTRIBUTING.md
Labels: documentation

#200 Fix image/DTO type mismatch in Google and Facebook Oauth providers
  src/Security/FacebookAuthenticator.php
  src/Security/GoogleAuthenticator.php
Labels: bug, backend

#197 Valuation: combine up votes and favourites
  migrations/Version20231103004800.php
  src/Entity/Contracts/FavouriteInterface.php
  src/Entity/Entry.php
  src/Entity/EntryComment.php
  src/Entity/Post.php
  src/Entity/PostComment.php
  src/Entity/Traits/RankingTrait.php
  src/Repository/EntryCommentRepository.php
  src/Repository/PostCommentRepository.php
  src/Service/FavouriteManager.php
Labels: enhancement, backend

#155 do not translate language options on post box
  templates/form/lang_select.html.twig
Labels: bug, low priority

#201 Fix duplicate key value for url_idx
  src/MessageHandler/LinkEmbedHandler.php
  src/Repository/EmbedRepository.php
Labels: enhancement, backend

#202 Improved admin guide
  docs/admin_guide.md
Labels: documentation, enhancement

#203 Add two additional Q/A + fix spelling
  FAQ.md
  README.md
  assets/utils/popover.js
  config/packages/nelmio_api_doc.yaml
  docker/compose.yml
  docker/docker-entrypoint
Labels: documentation

#205 swap readme github links from closed to merged
  README.md
Labels: documentation

#204 Renaming in Docker setup to mbin + Improved bare metal setup configs
  .gitignore
  README.md
  docker/Dockerfile
  docker/caddy/Caddyfile
  docker/compose.yml
  docker/php/conf.d/app.prod.ini
  docs/admin_guide.md
  docs/postman/kbin.postman_collection.json
  docs/postman/kbin.postman_environment.json
Labels: documentation, docker

#208 Add composer dump-env to post upgrade script
  bin/post-upgrade
Labels: enhancement, backend

#209 Improve .gitignore & FAQ
  .gitignore
  FAQ.md
Labels: documentation

#206 add quick links to change avatar and cover when viewing your own profile
  templates/components/user_box.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#210 Add enhancement PRs to README
  README.md
Labels: documentation

#211 Add postmill to credits
  README.md
Labels: documentation

#207 Translations update from Hosted Weblate
  translations/messages.nl.yaml
  translations/messages.uk.yaml
Labels: translation

#161 SubscriptionSidebar: improvements and default changes
  assets/styles/components/_sidebar-subscriptions.scss
  assets/styles/components/_sidebar.scss
  assets/styles/layout/_layout.scss
  src/Controller/User/ThemeSettingsController.php
  templates/base.html.twig
  templates/layout/_options_appearance.html.twig
  templates/layout/_sidebar.html.twig
  templates/layout/sidebar_subscriptions.html.twig
  translations/messages.de.yaml
  translations/messages.en.yaml
Labels: needs feedback, frontend

#225 update changes from sync 7
  templates/admin/_options.html.twig
  templates/admin/deletion_magazines.html.twig
  templates/admin/deletion_users.html.twig
  templates/components/entry_cross.html.twig
Labels: enhancement, frontend

#227 Limit where to shown the user box in sidebar
  templates/layout/_sidebar.html.twig
  templates/user/_info.html.twig
Labels: frontend

#228 fix user declaration on blocked domains page
  src/Controller/User/Profile/UserBlockController.php
Labels: bug

#229 add change my avatar and cover quick links to all user pages
  templates/components/user_box.html.twig
Labels: enhancement, frontend

#230 point reputation link to reputation path
  templates/user/_info.html.twig
Labels: enhancement, frontend

#234 Fix logic precedence in admin panel sidebar
  templates/user/overview.html.twig
Labels: bug

#236 update sidebar subscription links to stretch across row
  templates/layout/sidebar_subscriptions.html.twig
Labels: frontend

#237 Do not automatically subscribe admin OR users to new federated magazine lookups
  src/Service/MagazineManager.php
Labels: enhancement, backend

#238 Improve PostgeSQL documentation with fine tuning settings
  docs/admin_guide.md
Labels: documentation

#242 Correctly fetch remote NSFW info
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#243 Fix returning deleted admin
  src/Repository/UserRepository.php
Labels: bug, backend

#219 Kbin sync 8: Transfer request for ownership of abandoned magazines
  assets/styles/components/_entry.scss
  assets/styles/layout/_forms.scss
  assets/styles/layout/_tools.scss
  config/kbin_routes/admin.yaml
  config/kbin_routes/magazine.yaml
  config/kbin_routes/magazine_panel.yaml
  config/kbin_routes/user.yaml
  migrations/Version20231108084451.php
  src/Controller/Admin/AdminMagazineOwnershipRequestController.php
  src/Controller/Entry/EntryFrontController.php
  src/Controller/Magazine/MagazineAbandonedController.php
  src/Controller/Magazine/MagazineModeratorRequestController.php
  src/Controller/Magazine/MagazineOwnershipRequestController.php
  src/Controller/Magazine/MagazineRemoveSubscriptionsController.php
  src/Controller/Magazine/Panel/MagazineModeratorRequestsController.php
  src/Controller/User/UserRemoveFollowing.php
  src/DTO/ModeratorDto.php
  src/Entity/Magazine.php
  src/Entity/MagazineOwnershipRequest.php
  src/Entity/ModeratorRequest.php
  src/Entity/User.php
  src/MessageHandler/DeleteUserHandler.php
  src/MessageHandler/MagazinePurgeHandler.php
  src/Repository/MagazineOwnershipRequestRepository.php
  src/Repository/MagazineRepository.php
  src/Repository/ModeratorRequestRepository.php
  src/Security/Voter/MagazineVoter.php
  src/Service/MagazineManager.php
  src/Service/UserManager.php
  src/Twig/Runtime/UrlExtensionRuntime.php
  templates/admin/_options.html.twig
  templates/admin/deletion_magazines.html.twig
  templates/admin/deletion_users.html.twig
  templates/admin/magazine_ownership.html.twig
  templates/layout/_header.html.twig
  templates/layout/_header_nav.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/magazine/_options.html.twig
  templates/magazine/list_abandoned.html.twig
  templates/magazine/moderators.html.twig
  templates/magazine/panel/_options.html.twig
  templates/magazine/panel/general.html.twig
  templates/magazine/panel/moderator_requests.html.twig
  templates/user/overview.html.twig
  translations/messages.de.yaml
  translations/messages.en.yaml
  translations/messages.es.yaml
  translations/messages.fr.yaml
  translations/messages.ja.yaml
  translations/messages.nl.yaml
Labels: enhancement

#244 subscription sidebar - add back link hover style
  assets/styles/components/_sidebar.scss
Labels: bug, frontend

#247 Add badges to admins, mods and OPs in comments
  assets/styles/components/_comment.scss
  templates/components/entry_comment.html.twig
  templates/components/post_comment.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#250 Update Docker docs/compose.yml file with ghcr.io
  docker/compose.yml
  docs/docker_deployment_guide.md
Labels: documentation, docker

#252 Improve performance of subscription panel
  src/Repository/MagazineRepository.php
  src/Twig/Components/SidebarSubscriptionComponent.php
  src/Utils/SubscriptionSort.php
Labels: php, please review, backend

#246 nsfw entries - blur by default, unblur via JS hover event
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
Labels: frontend

#253 button changes to request for mod or ownership
  templates/magazine/moderators.html.twig
Labels: enhancement

#251 Kbin sync 9
  src/Controller/Entry/EntrySingleController.php
  src/Controller/Magazine/Panel/MagazineModeratorRequestsController.php
  src/Entity/Magazine.php
  src/EventSubscriber/VoteHandleSubscriber.php
  src/Repository/EntryRepository.php
  src/Repository/ModeratorRequestRepository.php
  src/Repository/PostRepository.php
  src/Twig/Components/EntriesCrossComponent.php
  templates/components/entries_cross.html.twig
  templates/entry/single.html.twig
  templates/magazine/moderators.html.twig
Labels: enhancement, frontend

#254 nsfw - add blurring of nsfw magazine icons
  assets/controllers/subject_controller.js
  assets/controllers/thumb_controller.js
  assets/styles/layout/_images.scss
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/magazine/_list.html.twig
Labels: enhancement, frontend

#256 Allow admins to create a sitewide notification below the header
  assets/styles/app.scss
  assets/styles/components/_announcement.scss
  migrations/Version20231113165549.php
  src/Controller/Admin/AdminPagesController.php
  src/Entity/Site.php
  src/Twig/Components/AnnouncementComponent.php
  templates/admin/_options.html.twig
  templates/admin/pages.html.twig
  templates/base.html.twig
  templates/components/announcement.html.twig
  translations/messages.en.yaml
Labels: enhancement

#261 update s3 adapter docs for not using ACL
  config/packages/oneup_flysystem.yaml
Labels: documentation

#260 add bot badges, add admin and global mod badges to user pages
  templates/components/entry_comment.html.twig
  templates/components/post_comment.html.twig
  templates/components/user_box.html.twig
  translations/messages.en.yaml
Labels: frontend

#264 Decrease proxy read timeout on Mercure
  docs/admin_guide.md
Labels: documentation

#265 hide nsfw magazine icons for logged out users, blur on mag sub/block pages
  assets/styles/components/_magazine.scss
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/layout/_magazine_activity_list.html.twig
  templates/magazine/_list.html.twig
Labels: frontend

#266 Fix frontend message enumeration when purged users threads are encountered
  templates/messages/front.html.twig
Labels: bug, frontend

#262 fix embed fetching occasionally persist results between calls
  src/Utils/Embed.php
Labels: bug, backend

#268 Improve Admin, Docker, Contrib, FAQ docs
  CONTRIBUTING.md
  FAQ.md
  docker/compose.yml
  docs/admin_guide.md
  docs/docker_deployment_guide.md
Labels: documentation, enhancement

#274 Update twig recipe
  config/packages/twig_component.yaml
  symfony.lock
Labels: enhancement, frontend

#273 Update phpunit v10
  .gitignore
  bin/phpunit
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Unit/Service/MentionManagerTest.php
  tests/Unit/Service/TagManagerTest.php
  tests/Unit/Utils/SluggerTest.php
Labels: enhancement

#271 Simply nodeinfo routing
  config/kbin_routes/activity_pub.yaml
  src/Controller/ActivityPub/NodeInfoController.php
Labels: enhancement, backend

#275 fix typo in example meta keywords
  .env.example
  .env.example_docker
Labels: bug

#272 Update annotations v2
  composer.json
  composer.lock
  src/DTO/BadgeDto.php
  src/DTO/MagazineDto.php
  src/DTO/ModeratorDto.php
  src/DTO/UserDto.php
  src/Validator/Unique.php
  src/Validator/UniqueValidator.php
Labels: enhancement, backend

#276 remove copy pasted vote up class on downvote button
  templates/components/vote.html.twig
Labels: bug

#267 Fix image cache resolve 302
  composer.lock
  config/packages/liip_imagine.yaml
  config/routes/liip_imagine.yaml
  docs/admin_guide.md
Labels: enhancement, frontend, backend

#278 Fix comment URL twig render, missing user object
  src/Controller/Entry/Comment/EntryCommentEditController.php
  src/Controller/Entry/Comment/EntryCommentResponseTrait.php
Labels: bug

#280 rework subscription panel buttons to use stimulus actions
  assets/controllers/subs_panel_controller.js
  config/packages/fos_js_routing.yaml
  public/js/fos_js_routes.json
  templates/layout/sidebar_subscriptions.html.twig
Labels: enhancement

#283 cleanup unused image assets
  assets/images/.DS_Store
  assets/images/ada.png
  assets/images/avatar.jpg
  assets/images/create-magazine-bg-orig.png
  assets/images/create-magazine-bg.png
  assets/images/entry_placeholder.png
  assets/images/render1.jpg
  assets/images/render1.png
  assets/images/render2.jpg
  assets/images/render2.png
  assets/images/render3.jpg
  assets/images/render3.png
  assets/images/sources.md
Labels: low priority

#185 removal of awards
  assets/styles/app.scss
  assets/styles/components/_awards.scss
  config/kbin_routes/magazine.yaml
  config/kbin_routes/page.yaml
  config/kbin_routes/user.yaml
  migrations/Version20231119012320.php
  src/Command/Update/AwardsInitCommand.php
  src/Controller/AwardListController.php
  src/Controller/Magazine/MagazineAwardController.php
  src/Controller/User/UserAwardController.php
  src/Entity/ApActivity.php
  src/Entity/Award.php
  src/Entity/AwardType.php
  src/Entity/Magazine.php
  src/Entity/User.php
  src/Repository/AwardRepository.php
  src/Repository/AwardTypeRepository.php
  templates/awards/_options.html.twig
  templates/awards/list_all.html.twig
  templates/layout/_footer.html.twig
  tests/Functional/Controller/AwardControllerTest.php
  translations/messages.en.yaml
Labels: please review, frontend

#285 Remove user facing ranking page, leftover crypto clean-up.
  config/kbin_routes/page.yaml
  migrations/Version20231120164429.php
  src/Controller/RankingController.php
  src/Entity/Entry.php
  templates/layout/_footer.html.twig
  templates/page/ranking.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend, backend

#282 Add db optimization migration
  migrations/Version20231121010453.php
Labels: enhancement, backend

#281 fix and adjust markdown rendering for images and links
  src/Markdown/CommonMark/EmbedElement.php
  src/Markdown/CommonMark/ExternalImagesRenderer.php
  src/Markdown/CommonMark/ExternalLinkRenderer.php
Labels: bug, enhancement

#291 add early out of sidebar selector when not a sidebar option
  assets/controllers/options_controller.js
Labels: bug

#295 Remove hardcoded Polish translations
  config/services.yaml
  src/Repository/Criteria.php
  src/Service/StatsManager.php
Labels: low priority

#292 inline moderate panel ux updates
  assets/controllers/subject_controller.js
  assets/styles/components/_comment.scss
  assets/styles/components/_entry.scss
  assets/styles/components/_post.scss
  assets/styles/components/_subject.scss
  src/Controller/Entry/Comment/EntryCommentChangeAdultController.php
  src/Controller/Entry/EntryChangeAdultController.php
  src/Controller/Post/Comment/PostCommentChangeAdultController.php
  src/Controller/Post/PostChangeAdultController.php
  templates/entry/_moderate_panel.html.twig
  templates/entry/comment/_moderate_panel.html.twig
  templates/entry/comment/moderate.html.twig
  templates/entry/moderate.html.twig
  templates/post/_moderate_panel.html.twig
  templates/post/comment/_moderate_panel.html.twig
  templates/post/comment/moderate.html.twig
  templates/post/moderate.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#296 fetch previews only once per page load
  assets/controllers/preview_controller.js
Labels: low priority

#301 fix media preview for crossposted entry component
  assets/styles/components/_entry.scss
  templates/components/entry_cross.html.twig
Labels: bug

#304 accept image attachment with appropiate mediaType set
  src/Service/ActivityPubManager.php
  src/Service/ImageManager.php
Labels: enhancement, activitypub

#302 recognize `image/webp` and some more media type as image
  src/Service/ImageManager.php
Labels: enhancement, frontend

#263 exiftool based image exif cleaner
  .env.example
  .env.example_docker
  config/services.yaml
  docker/Dockerfile
  docs/admin_guide.md
  src/EventSubscriber/Image/ExifCleanerSubscriber.php
  src/Repository/ImageRepository.php
  src/Utils/ExifCleanMode.php
  src/Utils/ExifCleaner.php
Labels: enhancement, backend

#235 Feature remote retrieval mod followers
  migrations/Version20231107204142.php
  migrations/Version20231112133420.php
  src/Controller/ActivityPub/Magazine/MagazineModeratorsController.php
  src/Controller/Admin/AdminMagazineOwnershipRequestController.php
  src/Controller/Admin/AdminModeratorController.php
  src/Controller/Api/Magazine/Admin/MagazineAddModeratorsApi.php
  src/Controller/Magazine/MagazineModController.php
  src/Controller/Magazine/MagazineOwnershipRequestController.php
  src/Controller/Magazine/Panel/MagazineModeratorController.php
  src/Controller/Magazine/Panel/MagazineModeratorRequestsController.php
  src/Controller/SearchController.php
  src/DTO/ModeratorDto.php
  src/Entity/Magazine.php
  src/Entity/Moderator.php
  src/Entity/Traits/ActivityPubActorTrait.php
  src/Entity/User.php
  src/Event/Magazine/MagazineModeratorAddedEvent.php
  src/Event/Magazine/MagazineModeratorRemovedEvent.php
  src/EventSubscriber/ActivityPub/GroupWebFingerSubscriber.php
  src/EventSubscriber/ActivityPub/MagazineModeratorAddedRemovedSubscriber.php
  src/EventSubscriber/ActivityPub/UserWebFingerProfileSubscriber.php
  src/EventSubscriber/ActivityPub/UserWebFingerSubscriber.php
  src/Exception/InboxForwardingException.php
  src/Factory/ActivityPub/AddRemoveFactory.php
  src/Factory/ActivityPub/GroupFactory.php
  src/Message/ActivityPub/Inbox/AddMessage.php
  src/Message/ActivityPub/Inbox/RemoveMessage.php
  src/Message/ActivityPub/Outbox/AddMessage.php
  src/Message/ActivityPub/Outbox/RemoveMessage.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/AddHandler.php
  src/MessageHandler/ActivityPub/Inbox/FollowHandler.php
  src/MessageHandler/ActivityPub/Inbox/RemoveHandler.php
  src/MessageHandler/ActivityPub/Outbox/AddHandler.php
  src/MessageHandler/ActivityPub/Outbox/RemoveHandler.php
  src/Repository/MagazineRepository.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/HttpSignature.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPub/SignatureValidator.php
  src/Service/ActivityPubManager.php
  src/Service/MagazineManager.php
  templates/components/magazine_box.html.twig
  templates/magazine/_moderators_sidebar.html.twig
Labels: activitypub, backend

#303 provide markdown body `source` property in AP entries/posts
  src/Factory/ActivityPub/EntryCommentNoteFactory.php
  src/Factory/ActivityPub/EntryPageFactory.php
  src/Factory/ActivityPub/PostCommentNoteFactory.php
  src/Factory/ActivityPub/PostNoteFactory.php
Labels: enhancement

#307 remove owner listing from magazine box
  templates/components/magazine_box.html.twig
Labels: frontend

#308 remote magazines - remove ability to apply for moderator or owner
  src/Controller/Magazine/MagazineModeratorRequestController.php
  src/Controller/Magazine/MagazineOwnershipRequestController.php
  src/Entity/Magazine.php
  src/Repository/MagazineRepository.php
  templates/magazine/_moderators_sidebar.html.twig
  templates/magazine/list_abandoned.html.twig
  templates/magazine/moderators.html.twig
  templates/magazine/panel/moderator_requests.html.twig
Labels: frontend

#309 remove online placeholders
  templates/entry/_info.html.twig
  templates/post/_info.html.twig
Labels: low priority, frontend

#310 fix clearing ap cache of local magazines
  src/EventSubscriber/ActivityPub/MagazineModeratorAddedRemovedSubscriber.php
Labels: bug

#311 hide moderator delete button in remote situations
  templates/magazine/_moderators_list.html.twig
Labels: frontend

#316 2fa - handle form errors with visible error and log
  src/Controller/User/Profile/User2FAController.php
  translations/messages.en.yaml
Labels: bug

#317 2fa - add active style to 2fa pages in user settings
  templates/user/settings/_options.html.twig
Labels: low priority, frontend

#320 Changes to report links and magazine report fix
  src/Repository/MagazineRepository.php
  templates/admin/_options.html.twig
  templates/components/report_list.html.twig
  templates/layout/_header.html.twig
  templates/magazine/panel/_options.html.twig
Labels: bug, frontend
