Repository MbinOrg/mbin, pull requests merged in 2024-10, with the labels that each got.

#1165 Fix the docker build error due to an old symfon/cache version
  composer.lock
Labels: dependencies, docker

#1168 Make the body not required while editing
  src/Form/EntryEditType.php
Labels: bug, frontend

#1169 Fix wrong title showing while editing a thread
  templates/entry/edit_entry.html.twig
Labels: bug, frontend

#1102 Check if the openssl_sign went OK
  src/Service/ActivityPub/ApHttpClient.php
Labels: bug, php, backend

#1166 Fix scheduler not running
  src/Message/ClearDeadMessagesMessage.php
  src/Message/ClearDeletedUserMessage.php
  src/Message/Contracts/SchedulerInterface.php
  src/MessageHandler/ClearDeadMessagesHandler.php
  src/MessageHandler/ClearDeletedUserHandler.php
  src/Scheduler/DeleteUserTaskProvider.php
  src/Scheduler/MbinTaskProvider.php
  src/Scheduler/Messages/ClearDeletedUserMessage.php
  src/Service/UserManager.php
Labels: bug, backend

#1177 Fix logic error in the posting restriction logic
  src/Entity/Magazine.php
Labels: bug, backend

#1178 Execute `npm audit fix`
  package-lock.json
Labels: dependencies, frontend, security

#1180 Exclude InvalidApPostException from rolling back the transaction
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
Labels: bug, backend

#1179 Use composer audit & npm audit
  .github/workflows/action.yaml
  README.md
  ci/Dockerfile
Labels: enhancement, dependencies, security

#1181 Redesign federation page
  templates/page/federation.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#1182 Fix toolbar broken in thread edit
  templates/entry/_form_edit.html.twig
Labels: bug, enhancement

#1183 Make related panels respect blocks
  src/Repository/BookmarkRepository.php
  src/Repository/EntryRepository.php
  src/Repository/MagazineRepository.php
  src/Repository/PostRepository.php
  src/Twig/Components/RelatedEntriesComponent.php
  src/Twig/Components/RelatedMagazinesComponent.php
  src/Twig/Components/RelatedPostsComponent.php
  src/Utils/SqlHelpers.php
Labels: enhancement, backend
