Repository MbinOrg/mbin, pull requests merged in 2024-06, with the labels that each got.

#801 Add Brazilian Portuguese and Danish language selectors
  README.md
  assets/controllers/timeago_controller.js
  templates/layout/_sidebar.html.twig
Labels: javascript, low priority, translation

#804 change sso authentication success route to front page
  src/Security/AzureAuthenticator.php
  src/Security/FacebookAuthenticator.php
  src/Security/GithubAuthenticator.php
  src/Security/GoogleAuthenticator.php
  src/Security/KeycloakAuthenticator.php
  src/Security/SimpleLoginAuthenticator.php
  src/Security/ZitadelAuthenticator.php
Labels: backend, sso

#806 Authentik SSO
  .env.example
  .env.example_docker
  config/kbin_routes/security.yaml
  config/packages/knpu_oauth2_client.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20240603230734.php
  src/Controller/Security/AuthentikController.php
  src/Entity/User.php
  src/Provider/Authentik.php
  src/Provider/AuthentikResourceOwner.php
  src/Security/AuthentikAuthenticator.php
  src/Twig/Components/LoginSocialsComponent.php
  templates/components/login_socials.html.twig
Labels: sso

#813 Docker caddy version bump
  docker/Dockerfile
Labels: dependencies, docker

#812 fix modlog error when the user adding/removing a moderator is null
  templates/modlog/_blocks.html.twig
Labels: bug, frontend

#818 Add support for the Privacy Portal OAUTH provider
  .env.example
  .env.example_docker
  composer.json
  composer.lock
  config/kbin_routes/security.yaml
  config/packages/knpu_oauth2_client.yaml
  config/packages/security.yaml
  config/services.yaml
  docs/01-user/user_guide.md
  migrations/Version20240612234046.php
  src/Controller/Security/PrivacyPortalController.php
  src/Entity/User.php
  src/Security/PrivacyPortalAuthenticator.php
  src/Twig/Components/LoginSocialsComponent.php
  symfony.lock
  templates/components/login_socials.html.twig
Labels: enhancement, backend, sso

#828 Improve modlog
  src/Controller/User/ThemeSettingsController.php
  templates/layout/_options_appearance.html.twig
  templates/modlog/_blocks.html.twig
  templates/modlog/front.html.twig
  templates/modlog/magazine.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#826 expose the `apFetchedAt` field of users and magazines for admins
  templates/components/magazine_box.html.twig
  templates/user/_info.html.twig
  translations/messages.en.yaml
Labels: frontend

#827 New/cake day
  src/Service/ActivityPubManager.php
  src/Service/SettingsManager.php
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/user/_info.html.twig
  templates/user/_user_popover.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend, activitypub

#834 Include content of audience tag in the receivers
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
Labels: enhancement, activitypub, backend

#835 Remove border radius on autocomplete form to fix letters from getting cutoff at the beginning of the item
  assets/styles/layout/_forms.scss
Labels: bug, frontend

#841 add aria attributes to cake day elements
  assets/styles/components/_popover.scss
  assets/styles/components/_sidebar.scss
  templates/user/_info.html.twig
  templates/user/_user_popover.html.twig
Labels: accessibility

#803 Try to fix wrong urls for images in the related panels
  src/Twig/Components/ActiveUsersComponent.php
  src/Twig/Components/RelatedEntriesComponent.php
  src/Twig/Components/RelatedMagazinesComponent.php
  src/Twig/Components/RelatedPostsComponent.php
Labels: bug, backend

#842 Update all npm packages and address dependabot security notice
  package-lock.json
Labels: dependencies, javascript

#847 Fix entries with not showing preview icon
  templates/components/entry.html.twig
Labels: bug, frontend

#846 Try to fix the "Table too large for buffer" messenger errors
  config/services.yaml
  src/Utils/AddErrorDetailsStampListener.php
Labels: bug, dependencies, backend

#825 improve `findActorOrCreate`
  src/Service/ActivityPubManager.php
Labels: activitypub, backend

#854 Add Filipino language selector to sidebar
  README.md
  templates/layout/_sidebar.html.twig
Labels: low priority, frontend, translation

#856 Translations update from Hosted Weblate
  translations/messages.bg.yaml
  translations/messages.da.yaml
  translations/messages.el.yaml
  translations/messages.eo.yaml
  translations/messages.es.yaml
  translations/messages.fil.yaml
  translations/messages.fr.yaml
  translations/messages.it.yaml
  translations/messages.ja.yaml
  translations/messages.nb_NO.yaml
  translations/messages.nl.yaml
  translations/messages.pl.yaml
  translations/messages.pt.yaml
  translations/messages.ru.yaml
  translations/messages.sv.yaml
  translations/messages.tr.yaml
  translations/messages.uk.yaml
  translations/messages.zh_TW.yaml
Labels: translation

#859 Fix rule mismatch on related entry front vs single
  src/Controller/Entry/EntryFrontController.php
Labels: bug

#853 Improve actor fetch
  migrations/Version20240625162714.php
  src/Entity/User.php
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#702 reduce frequency of `lastoriginupdate` db writes
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
Labels: backend

#862 Make outbox message handlers use the `DeliverManager`
  src/MessageHandler/ActivityPub/Outbox/AddHandler.php
  src/MessageHandler/ActivityPub/Outbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Outbox/DeleteHandler.php
  src/MessageHandler/ActivityPub/Outbox/FlagHandler.php
  src/MessageHandler/ActivityPub/Outbox/FollowHandler.php
  src/MessageHandler/ActivityPub/Outbox/RemoveHandler.php
  src/MessageHandler/ActivityPub/Outbox/UpdateHandler.php
  src/Service/DeliverManager.php
Labels: activitypub, backend

#870 findActorOrCreate was changed to search by apPublicUrl which is wrong, revert to apProfileId
  migrations/Version20240628142700.php
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend, high priority

#872 Fix/actor 404 json error
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/Service/ActivityPub/ApHttpClient.php
Labels: bug, activitypub, backend

#874 Add new exception to provide descriptive error (returned false) from `openssl_pkey_get_public` in signature validator
  src/Exception/InvalidUserPublicKeyException.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/Service/ActivityPub/SignatureValidator.php
Labels: enhancement, backend

#782 Add peertube support
  migrations/Version20240614120443.php
  src/DTO/EntryCommentDto.php
  src/DTO/EntryDto.php
  src/DTO/PostCommentDto.php
  src/DTO/PostDto.php
  src/Entity/Entry.php
  src/Entity/Traits/VotableTrait.php
  src/Factory/EntryCommentFactory.php
  src/Factory/EntryFactory.php
  src/Factory/PostCommentFactory.php
  src/Factory/PostFactory.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/FavouriteManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
  src/Service/VoteManager.php
  templates/components/boost.html.twig
  templates/components/vote.html.twig
  templates/entry/_options_activity.html.twig
Labels: enhancement, activitypub, backend

#876 Add Galician language support
  README.md
  assets/controllers/timeago_controller.js
  templates/layout/_sidebar.html.twig
Labels: translation

#877 Cleanup deprecation warnings in Symfony profiler pre 1.6.1 release
  config/packages/liip_imagine.yaml
  src/Provider/Authentik.php
  src/Provider/AuthentikResourceOwner.php
  src/Provider/SimpleLogin.php
  src/Provider/SimpleLoginResourceOwner.php
  src/Provider/Zitadel.php
  src/Provider/ZitadelResourceOwner.php
Labels: enhancement, php, low priority, backend

#830 Implement message federation and redesign message view
  assets/styles/components/_messages.scss
  assets/styles/components/_sidebar.scss
  config/kbin_routes/activity_pub.yaml
  migrations/Version20240603190838.php
  src/Controller/ActivityPub/MessageController.php
  src/Controller/Message/MessageCreateThreadController.php
  src/Controller/Message/MessageThreadController.php
  src/DTO/MessageDto.php
  src/Entity/Message.php
  src/Entity/MessageThread.php
  src/Factory/ActivityPub/ActivityFactory.php
  src/Factory/ActivityPub/MessageFactory.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/MessageHandler/ActivityPub/Outbox/CreateHandler.php
  src/Repository/ApActivityRepository.php
  src/Repository/MessageRepository.php
  src/Repository/MessageThreadRepository.php
  src/Service/ActivityPub/ContextsProvider.php
  src/Service/ActivityPub/Wrapper/CreateWrapper.php
  src/Service/ActivityPubManager.php
  src/Service/MessageManager.php
  templates/messages/_form_create.html.twig
  templates/messages/front.html.twig
  templates/messages/single.html.twig
  templates/notifications/_blocks.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend, activitypub, backend

#879 Add send direct message button to profile
  templates/components/user_actions.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend, translation
