Repository MbinOrg/mbin, pull requests merged in 2024-08, with the labels that each got.

#969 Add a leaf icon next to users and magazines if they are new
  assets/styles/components/_magazine.scss
  assets/styles/components/_sidebar.scss
  assets/styles/components/_user.scss
  src/Entity/Traits/CreatedAtTrait.php
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/user_box.html.twig
  templates/components/user_inline.html.twig
  templates/entry/_form_image.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/user/_user_popover.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#970 Update composer + npm packages and Symfony 7.1 upgrade
  composer.json
  composer.lock
  package-lock.json
  symfony.lock
Labels: dependencies, php, javascript

#973 Bump version for v1.7.0-rc
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#975 Remove the newly introduced jitter
  config/packages/messenger.yaml
Labels: dependencies, backend

#976 Revert accidental change
  templates/entry/_form_image.html.twig
Labels: bug, frontend

#968 Docs: Move mercure supervisor config, add media reverse proxy
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/02-configuration/nginx.md
  docs/02-admin/03-optional-features/mercure.md
Labels: documentation

#967 Docs: add s3 reverse proxy and migration to docs
  docs/02-admin/03-optional-features/s3_storage.md
Labels: documentation

#977 Clean up doctrine deprecation warnings
  config/packages/doctrine.yaml
  src/Kernel.php
Labels: backend

#971 When editing an entry only use one type
  assets/controllers/entry_link_create_controller.js
  src/Controller/Entry/EntryEditController.php
  src/Controller/Entry/EntryFormTrait.php
  src/Form/EntryEditType.php
  src/Form/EventListener/DisableFieldsOnEntryEdit.php
  src/Service/EntryManager.php
  templates/entry/_form_edit.html.twig
  templates/entry/edit_article.html.twig
  templates/entry/edit_entry.html.twig
  templates/entry/edit_image.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend, backend

#981 Recommend new installs use php8.3
  docs/02-admin/01-installation/bare_metal.md
Labels: documentation

#980 Bump docker php to 8.3 and rabbitmq versions
  docker/Dockerfile
  docker/compose.yml
Labels: docker

#982 Bump version to 1.7.0-rc2
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#983 Add joinmbin.org list of instance
  README.md
Labels: documentation

#985 Fix updating actor icons in specific cases
  src/Service/ActivityPubManager.php
Labels: enhancement, activitypub, backend

#986 Add a section for setting up push notifications
  docs/02-admin/04-running-mbin/first_setup.md
Labels: documentation

#988 fix some oddities about nodeinfo fetching/handling
  src/Payloads/NodeInfo/NodeInfoUsageUsers.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/RemoteInstanceManager.php
Labels: enhancement, backend

#989 preview controller memoize response
  assets/controllers/preview_controller.js
Labels: enhancement, frontend

#987 Replace MAX_IMAGE_BYTES constant in `ImageManager.php` with admin configurable environmental variable
  .env.example
  .env.example_docker
  config/services.yaml
  src/DTO/SettingsDto.php
  src/Service/ImageManager.php
  src/Service/SettingsManager.php
Labels: enhancement, backend

#991 Bump version to v1.7.0
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#992 Update docker php config to match bare metal guide
  docker/php/conf.d/app.ini
Labels: docker

#994 Update docker ini files to be a little more consistent with docs
  docker/php/conf.d/app.dev.ini
  docker/php/conf.d/app.ini
  docker/php/conf.d/app.prod.ini
Labels: docker

#997 Fix the error when saving the admin settings
  src/Service/SettingsManager.php
Labels: bug, backend

#998 Add posting restricted to mods to the API
  src/Controller/Api/Magazine/MagazineBaseApi.php
  src/DTO/MagazineRequestDto.php
  src/DTO/MagazineResponseDto.php
  src/DTO/MagazineUpdateRequestDto.php
  src/Factory/MagazineFactory.php
Labels: enhancement, backend, api

#995 Add user ban and suspension lists to admin panel
  config/kbin_routes/admin.yaml
  src/Controller/Admin/AdminUserController.php
  src/Controller/Admin/AdminUsersController.php
  src/Repository/UserRepository.php
  templates/admin/_options.html.twig
  templates/admin/users.html.twig
  translations/messages.en.yaml
Labels: enhancement

#1002 Add user password set/reset command to `bin/console`
  src/Command/UserPasswordCommand.php
Labels: enhancement, backend

#1004 Fix `ActivityHandler` errors regarding the payload
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
Labels: bug, activitypub, backend

#1005 Fix the managers checking wrong fields for editing permissions
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
Labels: bug, activitypub, backend, high priority

#1000 Allow admins to activate/verify accounts manually using the admin user panel
  config/kbin_routes/user.yaml
  src/Controller/User/Profile/UserVerifyController.php
  src/Service/UserManager.php
  templates/user/overview.html.twig
  translations/messages.en.yaml
Labels: enhancement

#1007 Stop banned or suspended users from notification creation on posts and entries
  src/Entity/User.php
  src/Service/Notification/EntryCommentNotificationManager.php
  src/Service/Notification/EntryNotificationManager.php
  src/Service/Notification/PostCommentNotificationManager.php
  src/Service/Notification/PostNotificationManager.php
Labels: enhancement, backend

#1008 Invalidate collection cache before getting collection for likes, dislikes and shares
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#1010 Bump version to 1.7.1-rc1
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#1011 Remove `\intval` around `MAX_IMAGE_BYTES` in `src/Service/SettingsManager.php`, breaks settings name resolution
  src/Service/SettingsManager.php
Labels: bug, high priority

#1012 Add trusted proxy config to framework configuration
  .env.example
  .env.example_docker
  config/packages/framework.yaml
Labels: enhancement, backend

#1015 Version bump for 1.7.1-rc2
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#1018 Make the API return the server public key and add a dedicated route for it
  config/kbin_routes/notification_api.yaml
  src/Controller/Api/Notification/NotificationPushApi.php
  src/DTO/ServerPublicKeyDto.php
Labels: bug, backend, api

#1020 Use the default when the value is zero
  src/Service/SettingsManager.php
Labels: bug, backend

#1019 Add an image too large error
  src/Controller/Entry/EntryCreateController.php
  src/Controller/Entry/EntryEditController.php
  src/Repository/ImageRepository.php
  templates/layout/_form_media.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend, backend

#1024 Revert "Make the API return the server public key and add a dedicated route for it"
  config/kbin_routes/notification_api.yaml
  src/Controller/Api/Notification/NotificationPushApi.php
  src/DTO/ServerPublicKeyDto.php
Labels: api

#1029 Fix user getting deleted when unregistering push
  src/Controller/Api/Notification/NotificationPushApi.php
  src/Entity/User.php
Labels: bug, backend, high priority

#1030 Fix `getAccessToken` always returning null
  src/Controller/Api/BaseApi.php
Labels: bug, backend

#1033 Fix UserPushSubscriptionManager using wrong AccessToken type
  src/Controller/Api/Notification/NotificationPushApi.php
  src/Service/Notification/UserPushSubscriptionManager.php
Labels: bug, backend, api

#1027 Bump version to 1.7.1-rc3
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#1034 Fix 500 error when a thread is empty
  src/Entity/MessageThread.php
  src/Repository/MessageThreadRepository.php
  templates/messages/front.html.twig
Labels: bug, backend

#1037 Update PHP Dependencies
  composer.lock
Labels: dependencies

#1013 Fix user soft delete and user account restore within 30 days
  src/Entity/Magazine.php
  src/Entity/User.php
  src/Security/UserChecker.php
  src/Service/UserManager.php
  templates/admin/deletion_magazines.html.twig
  templates/admin/deletion_users.html.twig
  translations/messages.en.yaml
Labels: bug, backend

#1028 Add cascade delete to report.considered_by_id
  migrations/Version20240815162107.php
  src/Entity/Report.php
Labels: backend

#1036 Only match magazine by hashtag if post was in random
  src/EventSubscriber/Post/PostCreateSubscriber.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
Labels: activitypub

#1040 Fix error when updating an actor and the instance has no nodeinfo endpoint
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/RemoteInstanceManager.php
Labels: bug, activitypub, backend

#1039 Return only the host as audience for remote magazines
  src/MessageHandler/ActivityPub/Outbox/CreateHandler.php
  src/Repository/MagazineRepository.php
Labels: bug, activitypub, backend

#1042 Bump Version to 1.7.1-rc4
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#1044 Add `isAdmin` and `isGlobalModerator` fields to user api response
  src/DTO/UserDto.php
  src/DTO/UserResponseDto.php
  src/DTO/UserSmallResponseDto.php
  src/Factory/UserFactory.php
Labels: enhancement, backend, api

#1043 Add field to all content response DTOs: `canAuthUserModerate`
  src/Controller/Api/Entry/EntriesBaseApi.php
  src/Controller/Api/Post/PostsBaseApi.php
  src/DTO/EntryCommentResponseDto.php
  src/DTO/EntryResponseDto.php
  src/DTO/PostCommentResponseDto.php
  src/DTO/PostResponseDto.php
  src/Factory/EntryCommentFactory.php
  src/Factory/PostCommentFactory.php
Labels: enhancement, backend, api

#1053 Add missing checks for banned instance
  src/Exception/InstanceBannedException.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#1057 actually building user agent in ProjectInfoService
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ProjectInfoService.php
Labels: backend

#1058 push navbar front route generation into twig func
  src/Twig/Runtime/FrontExtensionRuntime.php
  src/Twig/Runtime/NavbarExtensionRuntime.php
  templates/layout/_header_nav.html.twig
Labels: frontend

#1060 Fix AP context
  src/Service/ActivityPub/ContextsProvider.php
Labels: bug, activitypub

#1048 Edit the contributing docs
  CONTRIBUTING.md
Labels: documentation

#1049 Add a warning message when we hit the cache in post
  src/Service/ActivityPub/ApHttpClient.php
Labels: backend

#1051 Use different values for `timeout` and `max_duration`
  src/Service/ActivityPub/ApHttpClient.php
Labels: backend

#1050 Use a different cache key for activity object
  src/Service/ActivityPub/ApHttpClient.php
Labels: backend

#1065 Add the featured collection to the ap context
  src/Entity/Contracts/ActivityPubActivityInterface.php
Labels: activitypub, backend

#1055 Update _form_media.html.twig
  assets/styles/components/_media.scss
  templates/layout/_form_media.html.twig
Labels: frontend

#1069 Fix some leftover magazine undefined errors in the nav
  templates/layout/_header_nav.html.twig
Labels: bug, frontend
