Repository MbinOrg/mbin, pull requests merged in 2024-09, with the labels that each got.

#1059 chore: Create PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#1074 Add installation filler
  docs/02-admin/01-installation/README.md
Labels: documentation

#1076 Translations update from Hosted Weblate
  translations/messages.nl.yaml
Labels: translation

#1062 Update theme-dark.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/themes/_kbin.scss
Labels: frontend

#1066 Fix messenger deadlocks caused by cache locks
  src/Service/ActivityPub/ApHttpClient.php
Labels: enhancement

#1077 Fix the regex, so FF is no longer complaining
  src/Utils/RegPatterns.php
Labels: bug, backend

#1078 Use the latest pipeline docker image
  .github/workflows/action.yaml
  ci/Dockerfile
Labels: enhancement, docker

#1080 Use is defined on twig report notification objects
  templates/notifications/_blocks.html.twig
Labels: bug, frontend

#1079 Bump the version to 1.7.1-rc5
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#1070 move private vars out of some services/handlers
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/MessageHandler/DeleteUserHandler.php
Labels: enhancement

#1082 Add warning message to logger in case of invalid reg form submission
  src/Controller/Security/RegisterController.php
Labels: enhancement, backend

#1087 Do not stealth anti-spam error messages in log
  config/packages/antispam.yaml
Labels: enhancement, backend

#1086 Add trusted proxies to docs
  docs/02-admin/02-configuration/nginx.md
Labels: documentation

#1094 Add missing link to C4.md
  README.md
Labels: documentation

#1092 Update minor versions NPM packages
  package-lock.json
Labels: dependencies

#1091 Improve anti-spam config a little
  config/packages/antispam.yaml
Labels: enhancement

#1096 Remove dead kbin.run link in README
  README.md
Labels: documentation

#1093 Preparing for new release: remove rc5 label
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend

#1097 Add unofficial magazines
  README.md
Labels: documentation

#1098 Fix update actor failing because of a serializer error
  src/Service/RemoteInstanceManager.php
Labels: bug, backend

#1100 Check whether the author is blocked before notifying
  src/Repository/MagazineSubscriptionRepository.php
  src/Service/Notification/EntryCommentNotificationManager.php
  src/Service/Notification/EntryNotificationManager.php
  src/Service/Notification/NotificationTrait.php
  src/Service/Notification/PostCommentNotificationManager.php
  src/Service/Notification/PostNotificationManager.php
Labels: bug, backend

#1104 Add the downvotes mode to the .env.example
  .env.example
  .env.example_docker
Labels: documentation

#1110 Fix the downvote error
  src/Service/VoteManager.php
Labels: bug, backend

#1105 Clean-up push controller js
  assets/controllers/push_controller.js
Labels: enhancement

#1111 Clean up push controller js even more
  assets/controllers/push_controller.js
Labels: enhancement, javascript

#1108 Add spoiler to markdown editor
  assets/controllers/markdown_toolbar_controller.js
  templates/components/editor_toolbar.html.twig
  translations/messages.en.yaml
Labels: frontend

#1114 Also check if filePath is not null
  templates/layout/_magazine_activity_list.html.twig
Labels: bug, frontend

#1118 Null error on reported post comment notifications
  templates/notifications/_blocks.html.twig
Labels: bug, frontend

#1121 Fix 4th miscellaneous bug
  src/Service/ActivityPub/SignatureValidator.php
Labels: bug, backend

#1123 Fix 7th miscellaneous bug
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
Labels: bug, backend

#1124 Fix 2nd miscellaneous bug
  src/Service/ActivityPub/Page.php
Labels: bug, activitypub, backend

#1125 Fix 6th miscellaneous bug
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
Labels: bug, activitypub, backend

#1122 Fix 9th miscellaneous bug
  src/Service/ActivityPubManager.php
Labels: bug, backend

#1117 Fix null error when an instance does not have a nodeinfo endpoint
  src/Service/RemoteInstanceManager.php
Labels: bug, backend

#1101 Update composer PHP depedencies
  composer.json
  composer.lock
  src/Controller/User/Profile/User2FAController.php
  symfony.lock
Labels: dependencies, php

#1116 Disable badges for now
  src/Form/EntryArticleType.php
  src/Form/EntryEditType.php
  src/Form/EntryImageType.php
  src/Form/EntryLinkType.php
  templates/entry/_form_article.html.twig
  templates/entry/_form_edit.html.twig
  templates/entry/_form_image.html.twig
  templates/entry/_form_link.html.twig
  templates/entry/create_article.html.twig
  templates/entry/create_image.html.twig
  templates/entry/create_link.html.twig
  templates/entry/edit_entry.html.twig
  templates/magazine/create.html.twig
  templates/magazine/list_abandoned.html.twig
Labels: enhancement, frontend

#1128 Check on empty/null filePath image
  src/Command/ImageCacheCommand.php
Labels: bug, enhancement, backend

#1129 Check if EntryComment is defined and not null
  templates/entry/comment/view.html.twig
  translations/messages.en.yaml
Labels: bug, frontend

#1130 Improve invalid CSRF token logging + add explicit dependency
  composer.json
  composer.lock
  src/Controller/AbstractController.php
Labels: bug, help wanted

#1132 Add new command: "Remove failed messages command"
  src/Command/RemoveFailedMessagesCommand.php
Labels: enhancement, backend

#1133 Update docs with failed messages remove command
  docs/02-admin/04-running-mbin/messenger.md
Labels: documentation

#1134 Don't log full html pages (stop error log pollution)
  src/Service/ActivityPub/ApHttpClient.php
Labels: backend

#1135 Add explicit require dep phpseclib/phpseclib. Update minor releases o…
  composer.json
  composer.lock
Labels: bug, dependencies, high priority

#1136 Disable CSRF checks on some most-used forms
  src/Controller/BoostController.php
  src/Controller/Domain/DomainBlockController.php
  src/Controller/Domain/DomainSubController.php
  src/Controller/FavouriteController.php
  src/Controller/Magazine/MagazineBlockController.php
  src/Controller/Magazine/MagazineSubController.php
  src/Controller/Post/PostDeleteController.php
  src/Controller/User/Profile/UserNotificationController.php
  src/Controller/User/UserBlockController.php
  src/Controller/User/UserFollowController.php
  src/Controller/VoteController.php
Labels: enhancement, php, frontend, backend, security

#1143 Translations update from Hosted Weblate
  translations/messages.fr.yaml
  translations/messages.pt.yaml
  translations/messages.pt_BR.yaml
Labels: translation

#1140 Reduce error pollution even more on post request failures
  src/Service/ActivityPub/ApHttpClient.php
Labels: bug, enhancement

#1145 Store sessions in DB + improve cookies/sessions
  config/packages/framework.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20240923164233.php
  src/Controller/BoostController.php
  src/Controller/Domain/DomainBlockController.php
  src/Controller/Domain/DomainSubController.php
  src/Controller/FavouriteController.php
  src/Controller/Magazine/MagazineBlockController.php
  src/Controller/Magazine/MagazineSubController.php
  src/Controller/Post/PostDeleteController.php
  src/Controller/User/Profile/UserNotificationController.php
  src/Controller/User/UserBlockController.php
  src/Controller/User/UserFollowController.php
  src/Controller/VoteController.php
  templates/components/boost.html.twig
  templates/components/domain_sub.html.twig
  templates/components/favourite.html.twig
  templates/components/magazine_sub.html.twig
  templates/components/post.html.twig
  templates/components/user_actions.html.twig
  templates/components/vote.html.twig
  templates/notifications/front.html.twig
  templates/post/_menu.html.twig
  templates/post/_moderate_panel.html.twig
Labels: bug, enhancement, backend
