Repository MbinOrg/mbin, pull requests merged in 2024-07, with the labels that each got.

#881 Translations update from Hosted Weblate
  translations/messages.nl.yaml
Labels: translation

#882 Remove text from DM button, stops excessive text wrap on desktop view with three columns
  templates/components/user_actions.html.twig
Labels: low priority, frontend

#831 Federate pinned entries
  config/kbin_routes/activity_pub.yaml
  migrations/Version20240615225744.php
  src/Controller/ActivityPub/Magazine/MagazinePinnedController.php
  src/Controller/Api/Entry/Moderate/EntriesPinApi.php
  src/Controller/Entry/EntryPinController.php
  src/DTO/MagazineDto.php
  src/Entity/MagazineLog.php
  src/Entity/MagazineLogEntryPinned.php
  src/Entity/MagazineLogEntryUnpinned.php
  src/Entity/Traits/ActivityPubActorTrait.php
  src/Event/Entry/EntryPinEvent.php
  src/EventSubscriber/Entry/EntryPinSubscriber.php
  src/Factory/ActivityPub/AddRemoveFactory.php
  src/Factory/ActivityPub/GroupFactory.php
  src/Factory/MagazineFactory.php
  src/Message/ActivityPub/Inbox/CreateMessage.php
  src/Message/ActivityPub/Inbox/EntryPinMessage.php
  src/Message/ActivityPub/Outbox/EntryPinMessage.php
  src/Message/ActivityPub/Outbox/GenericAnnounceMessage.php
  src/MessageHandler/ActivityPub/Inbox/AddHandler.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/RemoveHandler.php
  src/MessageHandler/ActivityPub/Outbox/AddHandler.php
  src/MessageHandler/ActivityPub/Outbox/EntryPinMessageHandler.php
  src/MessageHandler/ActivityPub/Outbox/GenericAnnounceHandler.php
  src/MessageHandler/ActivityPub/Outbox/RemoveHandler.php
  src/Repository/ApActivityRepository.php
  src/Repository/EntryRepository.php
  src/Repository/MagazineRepository.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
  src/Service/EntryManager.php
  src/Service/MagazineManager.php
  src/Service/PostManager.php
  templates/modlog/_blocks.html.twig
  tests/Functional/Controller/Api/Entry/EntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/MagazineEntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/Moderate/EntryPinApiTest.php
  translations/messages.en.yaml
Labels: enhancement, activitypub, backend

#888 Translations update from Hosted Weblate
  translations/messages.nl.yaml
Labels: translation

#887 Add Discord SSO
  .env.example
  .env.example_docker
  composer.json
  composer.lock
  config/kbin_routes/security.yaml
  config/packages/knpu_oauth2_client.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20240706005744.php
  src/Controller/Security/DiscordController.php
  src/Entity/User.php
  src/Security/DiscordAuthenticator.php
  src/Twig/Components/LoginSocialsComponent.php
  templates/components/login_socials.html.twig
Labels: enhancement, backend, sso

#892 Add SSO documentation
  docs/02-admin/03-optional-features/sso.md
Labels: documentation, sso

#885 Add a lock to the handle if a user manually approves followers
  templates/components/user_box.html.twig
  templates/entry/_info.html.twig
  templates/post/_info.html.twig
  templates/user/_info.html.twig
  templates/user/_user_popover.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#894 Fix PrivacyPortal SSO
  src/Security/PrivacyPortalAuthenticator.php
Labels: bug, backend, sso

#896 Update sass loader and fix scss
  assets/styles/components/_domain.scss
  assets/styles/components/_login.scss
  assets/styles/components/_magazine.scss
  assets/styles/components/_sidebar.scss
  assets/styles/components/_user.scss
  package-lock.json
  package.json
Labels: dependencies

#897 Disable Ahrefs & Semrush bots
  public/robots.txt
Labels: enhancement

#903 Update minor versions
  package-lock.json
Labels: dependencies

#904 Fix the docs build
  docs/02-admin/03-optional-features/sso.md
Labels: bug, documentation

#907 Also block DataForSeoBot user-agent
  public/robots.txt
Labels: enhancement, backend

#905 Clean-up install notes
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/01-installation/docker.md
Labels: documentation

#909 Redirect to user profile settings on newly created SSO users
  src/Security/AuthentikAuthenticator.php
  src/Security/AzureAuthenticator.php
  src/Security/DiscordAuthenticator.php
  src/Security/FacebookAuthenticator.php
  src/Security/GithubAuthenticator.php
  src/Security/GoogleAuthenticator.php
  src/Security/KeycloakAuthenticator.php
  src/Security/PrivacyPortalAuthenticator.php
  src/Security/SimpleLoginAuthenticator.php
  src/Security/ZitadelAuthenticator.php
Labels: enhancement, sso

#912 Fix adviced -> advised
  docs/02-admin/01-installation/docker.md
Labels: documentation

#918 Increase lifetime remember me cookie
  config/packages/framework.yaml
  config/packages/security.yaml
Labels: enhancement

#923 Redirect to existing thread
  src/Controller/Message/MessageCreateThreadController.php
Labels: bug, backend

#922 Add option to hide related panels
  src/Controller/User/ThemeSettingsController.php
  templates/layout/_options_appearance.html.twig
  templates/layout/_sidebar.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#924 Futher extend robots.txt with AI bs user-agents
  public/robots.txt
Labels: enhancement

#925 Extend robots.txt
  public/robots.txt
Labels: enhancement

#926 Disallow terms & privacy policy
  public/robots.txt
Labels: enhancement

#915 Fix the LogicException when a report was rejected
  src/Factory/ContentManagerFactory.php
Labels: bug, backend

#928 Try to fix node build
  docker/Dockerfile
Labels: bug, dependencies, docker

#927 Add version info to robots.txt
  public/robots.txt
Labels: enhancement

#929 Fix the instructions to setup GitHub SSO
  docs/02-admin/03-optional-features/sso.md
Labels: documentation, sso

#931 Revert "Bump to newer version that also fixes npm install (#930)"
  docker/Dockerfile
Labels: docker

#932 Reapply "Bump to newer version that also fixes npm install (#930)"
  docker/Dockerfile
Labels: dependencies

#937 Update RabbitMQ installation
  docs/02-admin/01-installation/bare_metal.md
Labels: documentation

#783 Implement report notifications
  migrations/Version20240515122858.php
  src/Controller/Admin/AdminReportController.php
  src/Controller/Api/Notification/NotificationBaseApi.php
  src/Controller/Magazine/Panel/MagazineReportController.php
  src/Controller/ReportController.php
  src/Controller/User/Profile/UserReportsController.php
  src/Entity/Notification.php
  src/Entity/ReportApprovedNotification.php
  src/Entity/ReportCreatedNotification.php
  src/Entity/ReportRejectedNotification.php
  src/EventSubscriber/ReportApprovedSubscriber.php
  src/EventSubscriber/ReportRejectedSubscriber.php
  src/EventSubscriber/SubjectReportedSubscriber.php
  src/Repository/NotificationRepository.php
  src/Repository/ReportRepository.php
  src/Repository/UserRepository.php
  src/Schema/NotificationSchema.php
  src/Service/Notification/ReportNotificationManager.php
  templates/components/report_list.html.twig
  templates/notifications/_blocks.html.twig
  translations/messages.en.yaml
Labels: enhancement, backend

#893 When receiving an "Update" activity check permissions
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
Labels: bug, activitypub, backend, security

#942 Don't update actor if deleted
  src/Service/ActivityPubManager.php
Labels: enhancement, activitypub, backend

#941 Tombstones for deleted remote users
  src/Exception/UserDeletedException.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/DeleteUserHandler.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
Labels: enhancement, activitypub, backend

#940 Federate edits
  src/EventSubscriber/Entry/EntryPinSubscriber.php
  src/Message/ActivityPub/Outbox/GenericAnnounceMessage.php
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/MessageHandler/ActivityPub/Outbox/GenericAnnounceHandler.php
Labels: enhancement, activitypub

#945 increase issue stale time to a year
  .github/workflows/stale.yml
Labels: needs feedback

#949 Fix & update composer.lock
  .github/workflows/action.yaml
  ci/Dockerfile
  composer.lock
  src/Controller/AjaxController.php
  src/Controller/ReportController.php
  src/Controller/Security/ResetPasswordController.php
  src/Entity/EntryCommentCreatedNotification.php
  src/Entity/EntryCommentDeletedNotification.php
  src/Entity/EntryCommentEditedNotification.php
  src/Entity/EntryCommentMentionedNotification.php
  src/Entity/EntryCommentReplyNotification.php
  src/Entity/EntryCreatedNotification.php
  src/Entity/EntryDeletedNotification.php
  src/Entity/EntryEditedNotification.php
  src/Entity/EntryMentionedNotification.php
  src/Entity/MagazineBanNotification.php
  src/Entity/MessageNotification.php
  src/Entity/PostCommentCreatedNotification.php
  src/Entity/PostCommentDeletedNotification.php
  src/Entity/PostCommentEditedNotification.php
  src/Entity/PostCommentMentionedNotification.php
  src/Entity/PostCommentReplyNotification.php
  src/Entity/PostCreatedNotification.php
  src/Entity/PostDeletedNotification.php
  src/Entity/PostEditedNotification.php
  src/Entity/PostMentionedNotification.php
  src/Entity/ReportApprovedNotification.php
  src/Entity/ReportCreatedNotification.php
  src/Entity/ReportRejectedNotification.php
  src/Form/DataTransformer/BadgeCollectionToStringTransformer.php
  src/Form/Type/MagazineAutocompleteType.php
  src/Markdown/CommonMark/EmbedElement.php
  src/Pagination/CachingQueryAdapter.php
  src/Pagination/Pagerfanta.php
  src/Repository/UserRepository.php
  src/Service/ActivityPub/ApObjectExtractor.php
  src/Service/ActivityPub/Webfinger/WebFingerFactory.php
  src/Service/ActivityPubManager.php
  src/Service/ImageManager.php
  src/Service/MagazineManager.php
  src/Utils/Embed.php
  tests/Unit/Service/ActivityPub/SignatureValidatorTest.php
  tools/composer.lock
Labels: dependencies

#952 Fix PostgreSQL docs heading
  docs/02-admin/99-tuning/postgresql.md
Labels: documentation

#939 Add new instance table
  config/kbin_routes/instance_api.yaml
  migrations/Version20240628145441.php
  src/Controller/ActivityPub/NodeInfoController.php
  src/Controller/Api/Instance/InstanceRetrieveFederationApi.php
  src/Controller/FederationController.php
  src/DTO/InstanceDto.php
  src/DTO/InstancesDtoV2.php
  src/DTO/MagazineDto.php
  src/DTO/MagazineResponseDto.php
  src/DTO/UserDto.php
  src/DTO/UserResponseDto.php
  src/Entity/Instance.php
  src/Entity/Traits/UpdatedAtTrait.php
  src/Factory/MagazineFactory.php
  src/Factory/UserFactory.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
  src/Payloads/NodeInfo/NodeInfo.php
  src/Payloads/NodeInfo/NodeInfoServices.php
  src/Payloads/NodeInfo/NodeInfoSoftware.php
  src/Payloads/NodeInfo/NodeInfoSoftware21.php
  src/Payloads/NodeInfo/NodeInfoUsage.php
  src/Payloads/NodeInfo/NodeInfoUsageUsers.php
  src/Payloads/NodeInfo/WellKnownEndpoint.php
  src/Payloads/NodeInfo/WellKnownNodeInfo.php
  src/Repository/InstanceRepository.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPubManager.php
  src/Service/RemoteInstanceManager.php
  src/Twig/Extension/MagazineExtension.php
  src/Twig/Extension/UserExtension.php
  src/Twig/Runtime/MagazineExtensionRuntime.php
  src/Twig/Runtime/UserExtensionRuntime.php
  templates/components/magazine_box.html.twig
  templates/entry/_info.html.twig
  templates/page/federation.html.twig
  templates/user/_info.html.twig
  translations/messages.en.yaml
Labels: enhancement, activitypub, backend

#953 Add Redis page to docs
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/02-configuration/redis.md
Labels: documentation

#956 Improve Redis / KeyDB guide
  docs/02-admin/02-configuration/redis.md
Labels: documentation

#957 Fix left over mapping in `OAuth2UserConsent`
  src/Entity/OAuth2UserConsent.php
Labels: bug, backend

#959 Add php8.3 to docs + how to switch
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/02-configuration/README.md
  docs/02-admin/02-configuration/nginx.md
Labels: documentation

#960 Edit php 8.3 files
  docs/02-admin/01-installation/bare_metal.md
Labels: documentation

#961 Fix let's encrypt link in docs
  docs/02-admin/02-configuration/README.md
Labels: documentation

#951 Implement "posting restricted to mods"
  migrations/Version20240729174207.php
  src/Controller/Entry/EntryCreateController.php
  src/DTO/MagazineDto.php
  src/Entity/Magazine.php
  src/Exception/PostingRestrictedException.php
  src/Factory/ActivityPub/GroupFactory.php
  src/Factory/MagazineFactory.php
  src/Form/MagazineType.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
  src/Service/EntryManager.php
  src/Service/MagazineManager.php
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/entry/front.html.twig
  templates/magazine/_restricted_info.html.twig
  templates/magazine/panel/general.html.twig
  translations/messages.en.yaml
Labels: enhancement, activitypub, backend

#962 Add missing option to limit thread creation to mods on magazine creation
  src/Entity/Magazine.php
  src/Factory/MagazineFactory.php
  templates/magazine/create.html.twig
  translations/messages.en.yaml
Labels: bug, backend
