Repository MbinOrg/mbin, pull requests merged in 2024-11, with the labels that each got.

#1204 Fix dead instance query by allowing lastSuccessfulDeliver is null
  src/Entity/Instance.php
  src/Repository/InstanceRepository.php
Labels: bug, enhancement

#1208 Fix private comments being retrieved via API
  src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php
Labels: bug, backend, api

#1211 Fix delivering to oneself
  src/Service/DeliverManager.php
Labels: bug, activitypub, backend

#1222 Fix Symfony security issues
  composer.lock
Labels: dependencies, security, high priority

#1217 Improve Nginx logging, by introducing a separate inbox log
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/01-installation/docker.md
  docs/02-admin/02-configuration/nginx.md
  docs/02-admin/05-troubleshooting/bare_metal.md
Labels: documentation, enhancement

#1228 Add Valkey in header
  docs/02-admin/02-configuration/redis.md
Labels: documentation

#1231 Improved PostgreSQL config & setup
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/02-configuration/postgresql.md
  docs/02-admin/99-tuning/README.md
Labels: documentation

#1234 Fix ms to μs
  docs/02-admin/02-configuration/postgresql.md
Labels: documentation

#1221 Use keepalive (requires a upstream block) + Open file cache
  docs/02-admin/01-installation/docker.md
  docs/02-admin/02-configuration/nginx.md
Labels: documentation

#1238 Add default combined log format
  docs/02-admin/02-configuration/nginx.md
Labels: documentation

#1235 Throw UnrecoverableMessageHandlingException on 4xx
  src/Exception/InvalidApPostException.php
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
  src/Service/ActivityPub/ApHttpClient.php
Labels: bug, activitypub, backend

#1241 Improved action workflow
  .github/workflows/action.yaml
Labels: enhancement

#1236 Don't federate anything from the random magazine
  src/EventSubscriber/ActivityPub/GroupWebFingerProfileSubscriber.php
  src/EventSubscriber/ActivityPub/GroupWebFingerSubscriber.php
  src/MessageHandler/ActivityPub/Outbox/AddHandler.php
  src/MessageHandler/ActivityPub/Outbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Outbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Outbox/DeleteHandler.php
  src/MessageHandler/ActivityPub/Outbox/EntryPinMessageHandler.php
  src/MessageHandler/ActivityPub/Outbox/GenericAnnounceHandler.php
  src/MessageHandler/ActivityPub/Outbox/LikeHandler.php
  src/MessageHandler/ActivityPub/Outbox/RemoveHandler.php
  src/MessageHandler/ActivityPub/Outbox/UpdateHandler.php
Labels: bug, activitypub, backend

#1245 Fix min length issues for magazine description and rules
  src/DTO/MagazineDto.php
Labels: bug, backend, api

#1243 Fix mentions popping up in entry
  src/Markdown/CommonMark/ExternalLinkRenderer.php
Labels: bug, frontend

#1252 Rename 3rd party dev - > App developers
  docs/04-app_developers/README.md
  docs/README.md
Labels: documentation

#1253 Fix CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation

#1251 Expose local subscriber count to the API
  src/DTO/MagazineDto.php
  src/DTO/MagazineResponseDto.php
  src/Factory/MagazineFactory.php
Labels: enhancement, backend, api

#1249 Fix reports not triggering push notifications
  src/Service/Notification/ReportNotificationManager.php
Labels: bug, backend

#1248 Fix error on new magazines for admins
  templates/components/magazine_box.html.twig
Labels: bug, frontend

#1247 Update minor package + major qr-code package
  composer.json
  composer.lock
  src/Controller/User/Profile/User2FAController.php
Labels: enhancement, dependencies

#1254 Check for banned instances + improved logging
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/AddHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
  src/Service/SettingsManager.php
Labels: enhancement

#1255 Add remaining prefixes to logger on important files
  src/Controller/AjaxController.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/AddHandler.php
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/DislikeHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/MessageHandler/ActivityPub/Inbox/RemoveHandler.php
  src/MessageHandler/ActivityPub/Outbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Outbox/FlagHandler.php
  src/MessageHandler/ClearDeadMessagesHandler.php
  src/MessageHandler/ClearDeletedUserHandler.php
  src/MessageHandler/DeleteUserHandler.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPubManager.php
  src/Utils/Embed.php
Labels: documentation, enhancement
