Repository MbinOrg/mbin, pull requests merged in 2024-12, with the labels that each got.

#1278 Fix data action kbin -> mbin rename
  assets/controllers/mbin_controller.js
  assets/styles/components/_header.scss
  assets/styles/components/_sidebar-subscriptions.scss
  assets/styles/layout/_layout.scss
  src/Controller/User/ThemeSettingsController.php
  src/EventListener/LanguageListener.php
  src/Service/SettingsManager.php
  templates/base.html.twig
  templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig
  templates/layout/_header.html.twig
  templates/layout/_sidebar.html.twig
Labels: bug, enhancement

#1266 Update 04-image_metadata_cleaning.md
  docs/02-admin/03-optional-features/04-image_metadata_cleaning.md
Labels: documentation

#1277 Include last receive in the formula for dead instances
  src/Entity/Instance.php
  src/Repository/InstanceRepository.php
  translations/messages.en.yaml
Labels: activitypub, backend

#1275 Add new html to markdown converter for strikethrough support
  src/Service/ActivityPub/MarkdownConverter.php
  src/Service/ActivityPub/StrikethroughConverter.php
Labels: enhancement, backend

#1274 Improve command descriptions, add docs
  docs/02-admin/04-running-mbin/05-cli.md
  src/Command/ApImportObject.php
  src/Command/MagazineUnsubCommand.php
  src/Command/MoveEntriesByTagCommand.php
  src/Command/MovePostsByTagCommand.php
  src/Command/PostMagazinesUpdateCommand.php
  src/Command/RemoveAccountsMarkedForDeletion.php
  src/Command/RemoveDuplicatesCommand.php
  src/Command/SubMagazineCommand.php
  src/Command/UserUnsubCommand.php
Labels: documentation, enhancement

#1281 Remove using the AP id as the URL
  src/Factory/ActivityPub/EntryPageFactory.php
Labels: activitypub, backend

#1273 Add a magazine create command
  src/Command/MagazineCreateCommand.php
Labels: enhancement, backend

#1282 Make dependabot serve security updates for all npm packages
  .github/dependabot.yml
Labels: dependencies

#1283 Fix docs formatting
  docs/02-admin/04-running-mbin/05-cli.md
Labels: documentation

#1289 Fix null error on EntryPageFactory
  src/Factory/ActivityPub/EntryPageFactory.php
Labels: bug, backend, high priority

#1290 Add the new CLI section to the top level readme
  docs/02-admin/04-running-mbin/README.md
Labels: documentation

#1303 Add pdo_pgsql PHP extenstion
  ci/Dockerfile
Labels: enhancement, docker

#1299 Translations update from Hosted Weblate
  translations/messages.ru.yaml
Labels: translation

#1304 Improve PostgreSQL config even further
  docs/02-admin/02-configuration/04-postgresql.md
Labels: documentation, enhancement

#1311 Update npm minor version packages
  .github/workflows/action.yaml
  package-lock.json
Labels: dependencies

#1314 Add Timpibot to robots.txt
  public/robots.txt
Labels: enhancement

#1315 Improve Nginx access logs
  docs/02-admin/02-configuration/02-nginx.md
Labels: documentation, enhancement

#1316 Add two stage Nginx rate limit
  docs/02-admin/02-configuration/02-nginx.md
Labels: documentation, enhancement

#1280 Remove default local domain for entries
  docs/02-admin/04-running-mbin/05-cli.md
  src/Command/Update/RemoveRemoteEntriesFromLocalDomainCommand.php
  src/Service/DomainManager.php
Labels: backend

#1320 Add Devcontainer config (works with Codespaces)
  .devcontainer/apache-vhost.conf
  .devcontainer/devcontainer.json
  .github/dependabot.yml
Labels: enhancement, low priority, DX

#1329 Fix NPM warnings
  .eslintrc.json
  assets/app.js
  eslint.config.js
  package-lock.json
  package.json
  webpack.config.cjs
Labels: dependencies, javascript

#1332 Fix NPM warnings, round 2
  .eslintrc.json
  assets/app.js
  eslint.config.mjs
  package-lock.json
  package.json
Labels: javascript

#1328 Updated sass code
  assets/styles/app.scss
  assets/styles/components/_comment.scss
  assets/styles/components/_entry.scss
  assets/styles/components/_header.scss
  assets/styles/components/_login.scss
  assets/styles/components/_magazine.scss
  assets/styles/components/_media.scss
  assets/styles/components/_pagination.scss
  assets/styles/components/_post.scss
  assets/styles/components/_preview.scss
  assets/styles/components/_sidebar-subscriptions.scss
  assets/styles/components/_sidebar.scss
  assets/styles/components/_stats.scss
  assets/styles/components/_user.scss
  assets/styles/layout/_breakpoints.scss
  assets/styles/layout/_forms.scss
  assets/styles/layout/_layout.scss
  assets/styles/layout/_options.scss
  assets/styles/layout/_typo.scss
  assets/styles/mixins/animations.scss
  assets/styles/mixins/mbin.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-light.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
  assets/styles/themes/_default.scss
  assets/styles/themes/_solarized.scss
  webpack.config.js
Labels: frontend

#1333 Devcontainer improvements
  .devcontainer/.env.devcontainer
  .devcontainer/apache-vhost.conf
  .devcontainer/devcontainer.json
Labels: bug, low priority, DX

#1258 Add additional checks for banned instances + various code improvements along the way
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
  src/MessageHandler/ActivityPub/UpdateActorHandler.php
  src/MessageHandler/Notification/SentEntryCommentCreatedNotificationHandler.php
  src/MessageHandler/Notification/SentEntryCommentDeletedNotificationHandler.php
  src/MessageHandler/Notification/SentEntryCommentEditedNotificationHandler.php
  src/MessageHandler/Notification/SentEntryCreatedNotificationHandler.php
  src/MessageHandler/Notification/SentEntryDeletedNotificationHandler.php
  src/MessageHandler/Notification/SentEntryEditedNotificationHandler.php
  src/MessageHandler/Notification/SentMagazineBanNotificationHandler.php
  src/MessageHandler/Notification/SentPostCommentCreatedNotificationHandler.php
  src/MessageHandler/Notification/SentPostCommentDeletedNotificationHandler.php
  src/MessageHandler/Notification/SentPostCommentEditedNotificationHandler.php
  src/MessageHandler/Notification/SentPostCreatedNotificationHandler.php
  src/MessageHandler/Notification/SentPostDeletedNotificationHandler.php
  src/MessageHandler/Notification/SentPostEditedNotificationHandler.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/Wrapper/MentionsWrapper.php
  src/Service/ActivityPubManager.php
Labels: enhancement

#1345 Enable multi-core parallel PHP CS Fixer
  .php-cs-fixer.dist.php
Labels: enhancement, DX
