Repository MbinOrg/mbin, pull requests merged in 2024-01, with the labels that each got.

#388 Update symfony doctrine recipe to 2.11
  symfony.lock
Labels: dependencies, low priority

#326 Reject user actions when banned
  src/Security/Voter/EntryCommentVoter.php
  src/Security/Voter/EntryVoter.php
  src/Security/Voter/MagazineVoter.php
  src/Security/Voter/PostCommentVoter.php
  src/Security/Voter/PostVoter.php
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
Labels: backend

#384 Accessibility updates to FontAwesome icons
  assets/styles/components/_header.scss
  templates/admin/magazine_ownership.html.twig
  templates/admin/users.html.twig
  templates/base.html.twig
  templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig
  templates/components/_figure_entry.html.twig
  templates/components/_figure_image.html.twig
  templates/components/domain_sub.html.twig
  templates/components/editor_toolbar.html.twig
  templates/components/entry.html.twig
  templates/components/entry_cross.html.twig
  templates/components/login_socials.html.twig
  templates/components/magazine_sub.html.twig
  templates/components/post.html.twig
  templates/components/user_actions.html.twig
  templates/components/vote.html.twig
  templates/entry/_form_article.html.twig
  templates/entry/_form_image.html.twig
  templates/entry/_form_link.html.twig
  templates/entry/_list.html.twig
  templates/entry/_moderate_panel.html.twig
  templates/entry/_options.html.twig
  templates/entry/comment/_form_comment.html.twig
  templates/entry/comment/_moderate_panel.html.twig
  templates/entry/comment/_options.html.twig
  templates/entry/comment/create.html.twig
  templates/entry/comment/edit.html.twig
  templates/layout/_footer.html.twig
  templates/layout/_form_media.html.twig
  templates/layout/_header.html.twig
  templates/layout/_options_appearance.html.twig
  templates/layout/_options_font_size.html.twig
  templates/layout/_sidebar.html.twig
  templates/layout/sidebar_subscriptions.html.twig
  templates/magazine/_list.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/magazine/_options.html.twig
  templates/magazine/list_abandoned.html.twig
  templates/magazine/list_all.html.twig
  templates/magazine/moderators.html.twig
  templates/magazine/panel/general.html.twig
  templates/magazine/panel/moderator_requests.html.twig
  templates/notifications/front.html.twig
  templates/post/_form_post.html.twig
  templates/post/_moderate_panel.html.twig
  templates/post/_options.html.twig
  templates/post/comment/_form_comment.html.twig
  templates/post/comment/_moderate_panel.html.twig
  templates/post/comment/_options.html.twig
  templates/post/comment/create.html.twig
  templates/post/comment/edit.html.twig
  templates/post/edit.html.twig
  templates/search/front.html.twig
  templates/user/_info.html.twig
  templates/user/overview.html.twig
  templates/user/settings/general.html.twig
  translations/messages.en.yaml
Labels: accessibility

#389 Update InlineParserMatch regex in MentionLinkParser to correctly process usernames with hyphens
  src/Markdown/CommonMark/MentionLinkParser.php
Labels: bug, backend

#390 add oauth keycloak env vars to docker example
  .env.example_docker
Labels: low priority

#393 Add Russian translation selector, update timeago js controller
  README.md
  assets/controllers/timeago_controller.js
  templates/layout/_footer.html.twig
Labels: documentation, translation

#395 Handle exception on long embed URL length causing messages to go to failed queue
  src/Repository/EmbedRepository.php
Labels: enhancement, backend

#249 Feature remote reporting
  config/kbin_routes/activity_pub.yaml
  migrations/Version20231130203400.php
  src/Controller/ActivityPub/ReportController.php
  src/DTO/EntryDto.php
  src/DTO/PostCommentDto.php
  src/DTO/PostDto.php
  src/Entity/Contracts/ApiResourceInterface.php
  src/Entity/Entry.php
  src/Entity/EntryComment.php
  src/Entity/Magazine.php
  src/Entity/Post.php
  src/Entity/PostComment.php
  src/Entity/Report.php
  src/Entity/User.php
  src/EventSubscriber/SubjectReportedSubscriber.php
  src/Factory/ActivityPub/FlagFactory.php
  src/Message/ActivityPub/Inbox/FlagMessage.php
  src/Message/ActivityPub/Outbox/FlagMessage.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/FlagHandler.php
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
  src/MessageHandler/ActivityPub/Outbox/FlagHandler.php
Labels: enhancement, activitypub, backend

#401 Validate HTTP status codes in calls to `getCollectionObject`
  src/Service/ActivityPub/ApHttpClient.php
Labels: enhancement, backend

#402 Add various null/empty checks to abort or do nothing when encountered
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/Service/ActivityPubManager.php
Labels: enhancement, backend

#385 Move footer information into sidebar
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/components/_footer.scss
  assets/styles/components/_sidebar.scss
  assets/styles/layout/_layout.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-light.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
  assets/styles/themes/_kbin.scss
  assets/styles/themes/_tokyo-night.scss
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/base.html.twig
  templates/layout/_footer.html.twig
  templates/layout/_header.html.twig
  templates/layout/_sidebar.html.twig
  translations/messages.en.yaml
Labels: needs feedback, frontend

#413 Fix notifications of blocked users
  src/Service/MentionManager.php
  src/Service/Notification/EntryCommentNotificationManager.php
  src/Service/Notification/PostCommentNotificationManager.php
Labels: backend

#417 Increase HTTP timeout to 15 seconds
  src/Service/ActivityPub/ApHttpClient.php
Labels: activitypub, backend

#422 Translations update from Hosted Weblate
  translations/messages.de.yaml
Labels: translation

#419 correctly fetch display names of remote magazines
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#397 server assisted comment collapsing
  assets/controllers/comment_collapse_controller.js
  assets/controllers/subject_controller.js
  assets/controllers/subject_list_controller.js
  assets/styles/components/_comment.scss
  assets/styles/components/_post.scss
  assets/utils/kbin.js
  templates/components/_comment_collapse_button.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post_comment.html.twig
  translations/messages.en.yaml
Labels: enhancement, needs feedback, frontend

#432 Translations update from Hosted Weblate
  translations/messages.nl.yaml
Labels: translation

#434 add faq answer on getinstanceprivatekeys cache clear requirement
  FAQ.md
Labels: documentation

#369 Announce posts and comments
  src/Entity/User.php
  src/EventSubscriber/VoteHandleSubscriber.php
  src/Factory/ActivityPub/EntryCommentNoteFactory.php
  src/Factory/ActivityPub/EntryPageFactory.php
  src/Factory/ActivityPub/PostCommentNoteFactory.php
  src/Factory/ActivityPub/PostNoteFactory.php
  src/Message/ActivityPub/Outbox/AnnounceMessage.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/FollowHandler.php
  src/MessageHandler/ActivityPub/Outbox/AnnounceHandler.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
Labels: enhancement, activitypub, backend

#418 include remote users in followers collection
  src/Controller/ActivityPub/Magazine/MagazineFollowersController.php
Labels: bug, activitypub, backend

#437 remove forced line break on timestamps from sidebar components
  assets/styles/components/_sidebar.scss
Labels: low priority

#445 Improve handling of the random magazine and microblogs
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/MessageHandler/ActivityPub/Inbox/FollowHandler.php
  src/Service/ActivityPub/Wrapper/FollowResponseWrapper.php
Labels: bug, activitypub, backend, high priority

#450 Npm update
  package-lock.json
Labels: security

#455 Remove the local condition from magazine autocomplete
  src/Form/Type/MagazineAutocompleteType.php
Labels: bug, backend

#454 Add missing flash on contact form
  templates/page/contact.html.twig
Labels: bug, frontend, accessibility

#467 add user badges to entry and post templates
  assets/styles/_shared.scss
  assets/styles/app.scss
  assets/styles/components/_comment.scss
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/components/user_box.html.twig
Labels: frontend
