Repository MbinOrg/mbin, pull requests merged in 2024-02, with the labels that each got.

#462 Reread and update as well
  FAQ.md
Labels: documentation, enhancement

#461 Change the messenger queue layout
  FAQ.md
  config/packages/messenger.yaml
  docker/compose.yml
  docs/admin_guide.md
  docs/images/rabbit_messages_overview.png
  docs/images/rabbit_queue_overview.png
  docs/images/rabbit_queue_tab.png
  docs/images/rabbit_queue_tab_cut.png
Labels: enhancement, backend

#474 Translations update from Hosted Weblate
  translations/messages.bg.yaml
Labels: translation

#491 Using loading lazy on images
  templates/components/_figure_entry.html.twig
  templates/components/_figure_image.html.twig
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/related_entries.html.twig
  templates/components/related_posts.html.twig
  templates/components/user_avatar.html.twig
  templates/components/user_box.html.twig
  templates/components/user_image_component.html.twig
  templates/components/user_inline.html.twig
  templates/entry/_info.html.twig
  templates/layout/_magazine_activity_list.html.twig
  templates/layout/sidebar_subscriptions.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/post/_info.html.twig
  templates/user/_info.html.twig
  templates/user/_list.html.twig
  templates/user/consent.html.twig
Labels: enhancement, frontend

#493 Preload our logos
  templates/base.html.twig
  templates/layout/_sidebar.html.twig
Labels: enhancement, frontend

#490 FAQ: Explain 'all' messages
  FAQ.md
Labels: documentation

#489 FAQ: Retries three times
  FAQ.md
Labels: documentation

#492 FAQ: Typical message queue has changed
  FAQ.md
  docs/images/rabbit_small_load_typical.png
Labels: documentation

#502 Revert "Make usernames case insensitive everywhere"
  config/packages/doctrine.yaml
  migrations/Version20240204141515.php
Labels: bug, please review, backend, high priority

#504 Fix error on entries with an empty body
  src/Service/ActivityPub/ApObjectExtractor.php
Labels: bug, activitypub, backend

#396 somewhat fix phpunit so it could run functional tests again
  phpunit.xml.dist
  tests/Functional/Controller/Magazine/MagazineListControllerTest.php
  tests/bootstrap.php
Labels: please review

#503 Add column `last_origin_update` to magazine
  migrations/Version20240217141231.php
  src/Entity/Magazine.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
Labels: enhancement, activitypub, backend

#500 Add the correct cascading attribute to Entities
  migrations/Version20240216110804.php
  src/Entity/Badge.php
  src/Entity/Client.php
  src/Entity/Entry.php
  src/Entity/EntryComment.php
  src/Entity/EntryCommentCreatedNotification.php
  src/Entity/EntryCommentFavourite.php
  src/Entity/EntryCommentReport.php
  src/Entity/EntryCreatedNotification.php
  src/Entity/EntryDeletedNotification.php
  src/Entity/EntryEditedNotification.php
  src/Entity/EntryFavourite.php
  src/Entity/EntryMentionedNotification.php
  src/Entity/EntryReport.php
  src/Entity/Favourite.php
  src/Entity/Magazine.php
  src/Entity/MagazineBan.php
  src/Entity/MagazineBanNotification.php
  src/Entity/MagazineLog.php
  src/Entity/MagazineLogBan.php
  src/Entity/MagazineOwnershipRequest.php
  src/Entity/MagazineSubscription.php
  src/Entity/Message.php
  src/Entity/MessageNotification.php
  src/Entity/Moderator.php
  src/Entity/ModeratorRequest.php
  src/Entity/Notification.php
  src/Entity/OAuth2UserConsent.php
  src/Entity/Post.php
  src/Entity/PostComment.php
  src/Entity/PostCommentCreatedNotification.php
  src/Entity/PostCommentDeletedNotification.php
  src/Entity/PostCommentEditedNotification.php
  src/Entity/PostCommentFavourite.php
  src/Entity/PostCommentMentionedNotification.php
  src/Entity/PostCommentReplyNotification.php
  src/Entity/PostCommentReport.php
  src/Entity/PostCreatedNotification.php
  src/Entity/PostDeletedNotification.php
  src/Entity/PostEditedNotification.php
  src/Entity/PostFavourite.php
  src/Entity/PostMentionedNotification.php
  src/Entity/PostReport.php
  src/Entity/Report.php
  src/Entity/ResetPasswordRequest.php
  src/Entity/User.php
  src/Entity/ViewCounter.php
  src/Entity/Vote.php
Labels: enhancement, please review, backend

#510 Update Symfony packages + recipes+ NPM
  README.md
  assets/app.js
  assets/controllers.json
  composer.lock
  config/packages/dama_doctrine_test_bundle.yaml
  config/packages/doctrine.yaml
  config/packages/monolog.yaml
  config/packages/test/dama_doctrine_test_bundle.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  package-lock.json
  symfony.lock
  templates/base.html.twig
  tests/bootstrap.php
  webpack.config.js
Labels: dependencies

#512 Update remaining composer packages
  composer.lock
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Inbox/DeleteHandler.php
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/Validator/Unique.php
  tools/composer.lock
Labels: dependencies

#514 Fix circular message
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
Labels: bug, backend

#516 Remove route for down votes and make it a span
  config/kbin_routes/entry.yaml
  templates/entry/_options_activity.html.twig
  templates/entry/comment/_options_activity.html.twig
Labels: frontend

#523 Fix imagemanager not having a useful error message
  src/Service/ImageManager.php
Labels: bug, backend

#501 Improve handling of images
  migrations/Version20240217103834.php
  src/DTO/ImageDto.php
  src/Entity/Image.php
  src/MessageHandler/AttachEntryEmbedHandler.php
  src/Repository/ImageRepository.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/ImageManager.php
  src/Service/MagazineManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
  src/Service/UserManager.php
  src/Twig/Runtime/MediaExtensionRuntime.php
  templates/components/_figure_entry.html.twig
  templates/components/_figure_image.html.twig
  templates/components/entry.html.twig
  templates/components/entry_cross.html.twig
  templates/components/magazine_box.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/related_entries.html.twig
  templates/components/related_posts.html.twig
  templates/components/user_avatar.html.twig
  templates/components/user_box.html.twig
  templates/components/user_image_component.html.twig
  templates/components/user_inline.html.twig
  templates/entry/_form_article.html.twig
  templates/entry/_form_image.html.twig
  templates/entry/_form_link.html.twig
  templates/entry/_info.html.twig
  templates/entry/comment/_form_comment.html.twig
  templates/entry/front.html.twig
  templates/entry/single.html.twig
  templates/layout/sidebar_subscriptions.html.twig
  templates/magazine/_list.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/post/_form_post.html.twig
  templates/post/_info.html.twig
  templates/post/comment/_form_comment.html.twig
  templates/post/front.html.twig
  templates/post/single.html.twig
  templates/user/_info.html.twig
  templates/user/_list.html.twig
  templates/user/consent.html.twig
Labels: bug, enhancement, backend

#533 Set BaseEntityAutocompleteType with Ajax Form
  src/Form/Type/MagazineAutocompleteType.php
Labels: bug

#535 Update delete image message and handler to use object ids
  src/Entity/Image.php
  src/Message/DeleteImageMessage.php
  src/MessageHandler/DeleteImageHandler.php
Labels: bug, backend

#536 Allow null to be returned from MediaExtensionRuntime getPublicPath
  src/Twig/Runtime/MediaExtensionRuntime.php
Labels: bug, backend

#534 Consolidate markdown mention linking
  src/Markdown/CommonMark/CommunityLinkParser.php
  src/Markdown/CommonMark/MentionLinkParser.php
Labels: bug, backend

#532 Add entry domain to single view
  templates/components/entry.html.twig
Labels: enhancement, frontend
