Repository MbinOrg/mbin, pull requests merged in 2024-03, with the labels that each got.

#541 Fix rename of findUsersPaginated to findWithAboutPaginated
  src/Controller/Api/User/UserRetrieveApi.php
Labels: bug, backend, high priority, api

#542 apply padding around reduce option similar to other items
  assets/styles/layout/_options.scss
  templates/entry/_options_activity.html.twig
  templates/entry/comment/_options_activity.html.twig
Labels: low priority, frontend

#543 open domain urls in new window by default
  assets/styles/components/_entry.scss
  templates/components/entry.html.twig
Labels: needs feedback, frontend

#544 add preview grid areas to compact views
  assets/styles/components/_entry.scss
Labels: bug

#549 Add Matrix Chat badge
  README.md
Labels: documentation, enhancement

#34 Way of Working
  .github/workflows/stale.yml
  C4.md
  CONTRIBUTING.md
Labels: documentation, please review

#559 Fix clipping / z-index on visibility private posts
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
Labels: low priority

#554 Use title in "related magazines" panel
  templates/components/magazine_inline.html.twig
  templates/components/related_magazines.html.twig
Labels: frontend

#561 fix broken entry preview for non-image embeds
  templates/components/entry.html.twig
  templates/components/entry_cross.html.twig
Labels: bug

#560 Fix infinite scrolling on domain pages
  src/Controller/Domain/DomainFrontController.php
Labels: bug

#564 Fix User Statistics page not allowing federated filter
  config/kbin_routes/user.yaml
  src/Controller/User/Profile/UserStatsController.php
Labels: bug

#550 Improve AP documentation, debugging and error throwing
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPubManager.php
Labels: documentation, enhancement, backend

#565 Fix profile option being marked active when viewing other profiles
  templates/layout/_header.html.twig
Labels: bug

#403 Make comment timestamp links in most places
  src/Twig/Components/EntryCommentComponent.php
  templates/components/entry_comments_nested.html.twig
  templates/components/post_comments_nested.html.twig
  templates/entry/comment/_list.html.twig
  templates/entry/comment/edit.html.twig
  templates/entry/comment/moderate.html.twig
  templates/post/comment/_list.html.twig
  templates/post/comment/_preview.html.twig
  templates/post/comment/edit.html.twig
  templates/post/edit.html.twig
  templates/user/comments.html.twig
  templates/user/overview.html.twig
Labels: frontend

#569 Remove unused environment vars for API platform
  .env.example
  .env.example_docker
Labels: low priority

#572 Extend editability of username
  src/Security/Voter/UserVoter.php
Labels: bug, activitypub, backend, security

#573 Fix circular like/announce message
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
Labels: bug, activitypub, backend

#581 Fix GitHub oauth getId() type mismatch on assignment
  src/Security/GithubAuthenticator.php
Labels: bug, backend

#585 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#580 Add migration for unique indexes on favourite
  migrations/Version20240313222328.php
  src/Entity/Favourite.php
Labels: enhancement, backend, high priority

#579 Fix/boost regression
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Outbox/AnnounceHandler.php
  src/Service/ActivityPub/Wrapper/AnnounceWrapper.php
Labels: bug, activitypub, backend

#588 Adding the correct indexes for the user table
  migrations/Version20240315124130.php
  src/Entity/User.php
Labels: backend

#590 Bump npm follow-redirects package to 1.15.6
  package-lock.json
Labels: security

#589 Only count content from the last 30 days for active people
  src/Repository/UserRepository.php
Labels: backend

#591 Specify project name attribute in package.json
  package-lock.json
  package.json
Labels: dependencies, low priority

#586 Remove messager_app compose prd + minimal stability
  .dockerignore
  composer.json
  composer.lock
  docker/compose.prod.yml
Labels: enhancement, dependencies, docker

#601 fix extra padding on password preview icon
  assets/controllers/password_preview_controller.js
Labels: low priority

#602 Only do an update actor if it is actually necessary
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend, high priority

#436 First cut of showing federation staleness
  src/Twig/Extension/MagazineExtension.php
  src/Twig/Runtime/MagazineExtensionRuntime.php
  templates/magazine/_federated_info.html.twig
  translations/messages.en.yaml
Labels: frontend

#598 Fix reporting content in remote magazines and without a summary
  src/MessageHandler/ActivityPub/Inbox/FlagHandler.php
Labels: bug, activitypub, backend

#606 Remove empty panel from admin users pages when there is no pagination
  assets/controllers/subject_controller.js
  templates/admin/users.html.twig
Labels: low priority

#604 Add admin option to disable SSO registrations
  src/DTO/SettingsDto.php
  src/Form/SettingsType.php
  src/Security/FacebookAuthenticator.php
  src/Security/GithubAuthenticator.php
  src/Security/GoogleAuthenticator.php
  src/Security/KeycloakAuthenticator.php
  src/Service/SettingsManager.php
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/admin/settings.html.twig
  templates/user/register.html.twig
  tests/Functional/Controller/Api/Instance/Admin/InstanceSettingsRetrieveApiTest.php
  tests/Functional/Controller/Api/Instance/Admin/InstanceSettingsUpdateApiTest.php
  translations/messages.en.yaml
Labels: enhancement, security, sso

#429 Add support for Zitadel authentication
  .env.example
  .env.example_docker
  config/kbin_routes/security.yaml
  config/packages/knpu_oauth2_client.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20240113214751.php
  src/Controller/Security/ZitadelController.php
  src/Entity/User.php
  src/Provider/Zitadel.php
  src/Provider/ZitadelResourceOwner.php
  src/Security/ZitadelAuthenticator.php
  src/Twig/Components/LoginSocialsComponent.php
  templates/components/login_socials.html.twig
Labels: enhancement, sso

#607 Only unsubscribe or unfollow on block if already doing so
  src/Service/MagazineManager.php
  src/Service/UserManager.php
Labels: bug

#608 Add sso registration disabled check to zitadel
  src/Security/ZitadelAuthenticator.php
Labels: security, sso

#611 Add missing search method to domain repository
  src/Repository/DomainRepository.php
Labels: bug, backend

#612 Add dragonfly to the admin guide documentation
  docs/admin_guide.md
Labels: documentation, backend

#614 Address high severity npm security warning for node_modules/webpack-dev-middleware
  package-lock.json
Labels: dependencies, security

#615 set user report link to pending by default
  templates/user/settings/_options.html.twig
Labels: low priority

#616 Open remote mag/user links in new window, add mag link to sidebar
  templates/components/magazine_box.html.twig
  templates/magazine/_federated_info.html.twig
  templates/user/_federated_info.html.twig
  templates/user/_user_popover.html.twig
Labels: frontend

#617 add alt text as title as well
  templates/components/_figure_entry.html.twig
  templates/components/_figure_image.html.twig
Labels: low priority

#618 Update user popover for remote users
  assets/styles/components/_magazine.scss
  assets/styles/components/_user.scss
  assets/styles/layout/_alerts.scss
  templates/components/magazine_box.html.twig
  templates/entry/_info.html.twig
  templates/post/_info.html.twig
  templates/user/_user_popover.html.twig
  translations/messages.en.yaml
Labels: needs feedback, frontend

#522 Rework account deletion
  assets/styles/layout/_section.scss
  composer.json
  composer.lock
  config/kbin_routes/user.yaml
  docker/compose.yml
  docs/admin_guide.md
  migrations/Version20240317163312.php
  src/Command/DeleteUserCommand.php
  src/Command/RemoveAccountsMarkedForDeletion.php
  src/Controller/ActivityPub/User/UserController.php
  src/Controller/Api/User/Admin/UserDeleteApi.php
  src/Controller/Api/User/Admin/UserPurgeApi.php
  src/Controller/SearchController.php
  src/Controller/Security/ResendActivationEmailController.php
  src/Controller/User/AccountDeletionController.php
  src/Controller/User/UserDeleteController.php
  src/Controller/User/UserDeleteRequestController.php
  src/Controller/User/UserFrontController.php
  src/Controller/User/UserReputationController.php
  src/DTO/MagazineDto.php
  src/Entity/Magazine.php
  src/Entity/Report.php
  src/Factory/ActivityPub/TombstoneFactory.php
  src/Factory/MagazineFactory.php
  src/Form/UserAccountDeletionType.php
  src/Message/DeleteUserMessage.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/DeleteHandler.php
  src/MessageHandler/DeleteImageHandler.php
  src/MessageHandler/DeleteUserHandler.php
  src/Repository/ApActivityRepository.php
  src/Repository/EntryCommentRepository.php
  src/Repository/EntryRepository.php
  src/Repository/SearchRepository.php
  src/Repository/StatsContentRepository.php
  src/Repository/StatsRepository.php
  src/Repository/StatsViewsRepository.php
  src/Repository/StatsVotesRepository.php
  src/Repository/UserRepository.php
  src/Repository/VoteRepository.php
  src/Scheduler/DeleteUserTaskProvider.php
  src/Scheduler/Handlers/ClearDeletedUserHandler.php
  src/Scheduler/Messages/ClearDeletedUserMessage.php
  src/Security/UserChecker.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/Wrapper/DeleteWrapper.php
  src/Service/ActivityPubManager.php
  src/Service/InstanceStatsManager.php
  src/Service/MagazineManager.php
  src/Service/SearchManager.php
  src/Service/StatsManager.php
  src/Service/UserManager.php
  templates/admin/users.html.twig
  templates/components/user_actions.html.twig
  templates/user/overview.html.twig
  templates/user/settings/_options.html.twig
  templates/user/settings/account_deletion.html.twig
  templates/user/settings/general.html.twig
  translations/messages.en.yaml
Labels: enhancement, activitypub, backend

#595 Rework messenger config
  config/packages/messenger.yaml
  config/packages/test/messenger.yaml
  docker/compose.yml
  docs/admin_guide.md
  src/Message/ActivityPub/CreateActorMessage.php
  src/Message/ActivityPub/Inbox/ActivityMessage.php
  src/Message/ActivityPub/Inbox/AddMessage.php
  src/Message/ActivityPub/Inbox/AnnounceMessage.php
  src/Message/ActivityPub/Inbox/ChainActivityMessage.php
  src/Message/ActivityPub/Inbox/CreateMessage.php
  src/Message/ActivityPub/Inbox/DeleteMessage.php
  src/Message/ActivityPub/Inbox/DislikeMessage.php
  src/Message/ActivityPub/Inbox/FlagMessage.php
  src/Message/ActivityPub/Inbox/FollowMessage.php
  src/Message/ActivityPub/Inbox/LikeMessage.php
  src/Message/ActivityPub/Inbox/RemoveMessage.php
  src/Message/ActivityPub/Inbox/UpdateMessage.php
  src/Message/ActivityPub/Outbox/AddMessage.php
  src/Message/ActivityPub/Outbox/AnnounceLikeMessage.php
  src/Message/ActivityPub/Outbox/AnnounceMessage.php
  src/Message/ActivityPub/Outbox/CreateMessage.php
  src/Message/ActivityPub/Outbox/DeleteMessage.php
  src/Message/ActivityPub/Outbox/DeliverMessage.php
  src/Message/ActivityPub/Outbox/FlagMessage.php
  src/Message/ActivityPub/Outbox/FollowMessage.php
  src/Message/ActivityPub/Outbox/LikeMessage.php
  src/Message/ActivityPub/Outbox/RemoveMessage.php
  src/Message/ActivityPub/Outbox/UpdateMessage.php
  src/Message/ActivityPub/UpdateActorMessage.php
  src/Message/Contracts/ActivityPubInboxInterface.php
  src/Message/Contracts/ActivityPubInboxReceiveInterface.php
  src/Message/Contracts/ActivityPubOutboxDeliverInterface.php
  src/Message/Contracts/ActivityPubOutboxInterface.php
  src/Message/Contracts/ActivityPubResolveInterface.php
  src/Message/EntryEmbedMessage.php
  src/Message/MagazinePurgeMessage.php
  src/Message/Notification/EntryCommentDeletedNotificationMessage.php
  src/Message/Notification/EntryDeletedNotificationMessage.php
  src/Message/Notification/PostCommentDeletedNotificationMessage.php
  src/Message/Notification/PostDeletedNotificationMessage.php
  src/MessageHandler/ActivityPub/CreateActorHandler.php
Labels: enhancement, dependencies, backend

#624 Add resolve queue explanation to admin guide
  docs/admin_guide.md
Labels: documentation

#597 Rewrite the `ChainActivityHandler`
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/DislikeHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/Repository/ApActivityRepository.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
Labels: activitypub, backend

#625 Bump Version to 1.5.0
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: pr pending

#626 Translations update from Hosted Weblate
  translations/messages.nl.yaml
Labels: translation

#627 Fix error pollution on null $user object
  src/Service/ActivityPubManager.php
Labels: enhancement, backend

#631 Use the correct names for RabbitMQ & PostgreSQL
  docs/admin_guide.md
Labels: documentation

#634 Fix Dragonfly redis compatibility config
  docs/admin_guide.md
Labels: documentation

#636 Fix width class missing if `KBIN_PAGE_WIDTH` has not been set
  templates/base.html.twig
Labels: bug, frontend

#635 Fix list display in magazine description
  assets/styles/components/_magazine.scss
Labels: frontend

#638 restore css to limit figure preview size
  assets/styles/components/_figure_image.scss
Labels: frontend, accessibility

#645 Hotfix: Fix email sent
  config/packages/messenger.yaml
Labels: bug, high priority

#603 Remove password and 2fa options for sso controlled users
  assets/styles/layout/_forms.scss
  src/Controller/User/Profile/User2FAController.php
  src/Controller/User/Profile/UserEditController.php
  src/Entity/User.php
  templates/user/settings/_options.html.twig
  templates/user/settings/email.html.twig
Labels: sso

#641 Bye Dragonfly, Hello KeyDB
  docs/admin_guide.md
Labels: documentation
