Repository MbinOrg/mbin, pull requests merged in 2024-05, with the labels that each got.

#748 Add null check to magazine description/rules before getting passed to markdown converter
  src/Factory/ActivityPub/GroupFactory.php
Labels: bug, backend

#756 Fix 2fa redirect not being triggered on login
  src/Security/Voter/PrivateInstanceVoter.php
Labels: bug

#761 Update cache action to v4
  .github/workflows/action.yaml
Labels: enhancement

#740 Add admin panel option to enable/disable SSO only mode
  config/services.yaml
  src/Controller/Security/LoginController.php
  src/Controller/Security/RegisterController.php
  src/DTO/SettingsDto.php
  src/Form/SettingsType.php
  src/Service/SettingsManager.php
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/admin/settings.html.twig
  templates/user/login.html.twig
  translations/messages.en.yaml
Labels: enhancement

#767 fix visibility info no longer being shown
  src/Controller/Entry/EntryFrontController.php
  templates/post/front.html.twig
  templates/user/_visibility_info.html.twig
Labels: bug

#769 fix construct variable usage on registercontroller
  src/Controller/Security/RegisterController.php
Labels: bug, high priority

#706 Restyle login/register social and action button sections
  assets/styles/components/_login.scss
  assets/styles/layout/_forms.scss
  src/DTO/SettingsDto.php
  src/Form/SettingsType.php
  src/Service/SettingsManager.php
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/admin/settings.html.twig
  templates/components/login_socials.html.twig
  templates/components/user_form_actions.html.twig
  templates/resend_verification_email/resend.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/user/login.html.twig
  templates/user/register.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#766 connect mercure endpoint url to noti controller directly
  assets/controllers/notifications_controller.js
  assets/utils/event-source.js
  templates/base.html.twig
Labels: enhancement, backend

#739 webfinger controller event pass request once
  src/Controller/ActivityPub/WebFingerController.php
  src/Event/ActivityPub/WebfingerResponseEvent.php
  src/EventSubscriber/ActivityPub/GroupWebFingerProfileSubscriber.php
  src/EventSubscriber/ActivityPub/GroupWebFingerSubscriber.php
  src/EventSubscriber/ActivityPub/UserWebFingerProfileSubscriber.php
  src/EventSubscriber/ActivityPub/UserWebFingerSubscriber.php
  src/Service/ActivityPub/Webfinger/WebFingerParameters.php
Labels: backend

#775 Exclude `node_modules` and `vendor` directories from PHP linter
  .php-cs-fixer.dist.php
Labels: php, low priority

#774 Make 2fa input field required to submit form
  templates/user/2fa.html.twig
Labels: low priority

#778 Add note to lint docs
  docs/04-contributing/linting.md
Labels: documentation

#779 Extend AI user agent bot ban list
  public/robots.txt
Labels: enhancement

#762 Add SimpleLogin SSO
  .env.example
  .env.example_docker
  config/kbin_routes/security.yaml
  config/packages/knpu_oauth2_client.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20240503224350.php
  src/Controller/Security/SimpleLoginController.php
  src/Entity/User.php
  src/Provider/SimpleLogin.php
  src/Provider/SimpleLoginResourceOwner.php
  src/Security/SimpleLoginAuthenticator.php
  src/Twig/Components/LoginSocialsComponent.php
  templates/components/login_socials.html.twig
Labels: enhancement, sso

#781 Add available simple-icons to SimpleLogin SSO
  assets/styles/app.scss
  package-lock.json
  package.json
  templates/components/login_socials.html.twig
Labels: low priority, frontend, sso

#773 Fixes to user filters on active user sidebar and people pages
  src/Controller/Magazine/MagazinePeopleFrontController.php
  src/Repository/UserRepository.php
Labels: bug

#796 Include image blur hash in `ImageDto`
  src/DTO/ImageDto.php
  src/Factory/ImageFactory.php
Labels: backend, api

#793 Update packages
  composer.lock
  package-lock.json
  symfony.lock
Labels: dependencies

#795 Fix/outgoing deletes
  migrations/Version20240529115400.php
  src/Controller/ActivityPub/Magazine/MagazineModeratorsController.php
  src/Entity/Magazine.php
  src/EventSubscriber/Entry/EntryBeforeDeleteSubscriber.php
  src/EventSubscriber/Entry/EntryDeleteSubscriber.php
  src/EventSubscriber/EntryComment/EntryCommentBeforeDeleteSubscriber.php
  src/EventSubscriber/EntryComment/EntryCommentDeleteSubscriber.php
  src/EventSubscriber/Post/PostBeforeDeleteSubscriber.php
  src/EventSubscriber/Post/PostDeleteSubscriber.php
  src/EventSubscriber/PostComment/PostCommentBeforeDeleteSubscriber.php
  src/EventSubscriber/PostComment/PostCommentDeleteSubscriber.php
  src/Factory/MagazineFactory.php
  src/MessageHandler/ActivityPub/Inbox/RemoveHandler.php
  src/Repository/MagazineRepository.php
  src/Service/ActivityPub/Wrapper/DeleteWrapper.php
  src/Service/ActivityPubManager.php
  src/Service/EntryCommentManager.php
  src/Service/EntryManager.php
  src/Service/MagazineManager.php
  src/Service/PostCommentManager.php
  src/Service/PostManager.php
  templates/magazine/_moderators_sidebar.html.twig
Labels: activitypub, backend

#800 Update Docker caddy builder version
  docker/Dockerfile
Labels: dependencies, docker
