Repository MbinOrg/mbin, pull requests merged in 2024-04, with the labels that each got.

#652 Rename yarn to npm
  docs/admin_guide.md
Labels: documentation

#651 fix some minor css typos
  assets/styles/emails.scss
  assets/styles/layout/_forms.scss
  assets/styles/layout/_layout.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
Labels: low priority

#656 Fix missing delete cascade on MessageThread
  migrations/Version20240402190028.php
  src/Entity/Message.php
  src/Entity/MessageThread.php
Labels: bug, high priority

#653 Remove obsolete package-versions-deprecated
  composer.json
  composer.lock
  symfony.lock
Labels: enhancement, dependencies

#658 npm package bump, fix recent warnings in security audit
  package-lock.json
Labels: dependencies, low priority

#660 Update Symfony console recipe
  bin/console
  symfony.lock
Labels: dependencies, low priority

#667 use markdown alert syntax for various emphasis in documentation
  CONTRIBUTING.md
  FAQ.md
  README.md
  UPGRADE.md
  docs/admin_guide.md
  docs/docker_deployment_guide.md
  docs/oauth2_guide.md
Labels: low priority

#669 Fix typo in admin guide warning message
  docs/admin_guide.md
Labels: low priority

#453 UI filter changes
  assets/controllers/options_controller.js
  assets/styles/components/_sidebar.scss
  assets/styles/layout/_breakpoints.scss
  assets/styles/layout/_options.scss
  config/kbin_routes/front.yaml
  config/kbin_routes/post.yaml
  config/services.yaml
  src/Controller/AbstractController.php
  src/Controller/Entry/Comment/EntryCommentFrontController.php
  src/Controller/Entry/EntryFrontController.php
  src/Controller/Magazine/MagazineListController.php
  src/Controller/Post/PostFrontController.php
  src/Controller/Security/LoginController.php
  src/Controller/Security/RegisterController.php
  src/Controller/User/ThemeSettingsController.php
  src/EventListener/UserHomepageListener.php
  src/Repository/Criteria.php
  src/Repository/EntryRepository.php
  src/Security/KbinAuthenticator.php
  src/Twig/Runtime/NavbarExtensionRuntime.php
  src/Twig/Runtime/UrlExtensionRuntime.php
  templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig
  templates/entry/_options.html.twig
  templates/layout/_header.html.twig
  templates/layout/_header_bread.html.twig
  templates/layout/_header_nav.html.twig
  templates/layout/_options_appearance.html.twig
  templates/layout/_sidebar.html.twig
  templates/layout/_topbar.html.twig
  templates/post/_options.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#659 Translations update from Hosted Weblate
  translations/messages.bg.yaml
  translations/messages.da.yaml
Labels: translation

#610 Admin option - Restrict magazine creation to admins/global moderators
  src/Controller/Magazine/MagazineCreateController.php
  src/DTO/SettingsDto.php
  src/Form/SettingsType.php
  src/Service/MagazineManager.php
  src/Service/SettingsManager.php
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/admin/settings.html.twig
  templates/layout/_header.html.twig
  templates/layout/_sidebar.html.twig
  tests/Functional/Controller/Api/Instance/Admin/InstanceSettingsRetrieveApiTest.php
  tests/Functional/Controller/Api/Instance/Admin/InstanceSettingsUpdateApiTest.php
  translations/messages.en.yaml
Labels: enhancement, please review

#674 fix microblog post form missing from microblog pages
  templates/post/front.html.twig
  templates/user/_visibility_info.html.twig
Labels: bug

#587 Update crosspost component, include entry title
  assets/styles/components/_entry.scss
  src/Twig/Components/EntriesCrossComponent.php
  templates/components/entries_cross.html.twig
  templates/components/entry_cross.html.twig
  translations/messages.en.yaml
Labels: please review, frontend

#665 feat: implement microsoft azure oidc connector
  .env.example
  .env.example_docker
  composer.json
  composer.lock
  config/kbin_routes/security.yaml
  config/packages/knpu_oauth2_client.yaml
  config/packages/security.yaml
  config/services.yaml
  migrations/Version20240405134821.php
  src/Controller/Security/AzureController.php
  src/Entity/User.php
  src/Security/AzureAuthenticator.php
  src/Twig/Components/LoginSocialsComponent.php
  templates/components/login_socials.html.twig
Labels: enhancement, backend, sso

#666 Removal of view counters and associated statistics
  composer.json
  composer.lock
  config/bundles.php
  config/kbin_routes/instance_api.yaml
  config/kbin_routes/moderation_api.yaml
  config/kbin_serialization/entry.yaml
  config/packages/tchoulom_view_counter.yaml
  config/services.yaml
  migrations/Version20240405131611.php
  src/Controller/Api/Instance/InstanceRetrieveStatsApi.php
  src/Controller/Api/Magazine/Admin/MagazineRetrieveStatsApi.php
  src/Controller/Magazine/Panel/MagazineStatsController.php
  src/Controller/StatsController.php
  src/Controller/User/Profile/UserStatsController.php
  src/DTO/EntryDto.php
  src/DTO/EntryResponseDto.php
  src/DTO/ViewStatsResponseDto.php
  src/Entity/Entry.php
  src/Entity/User.php
  src/Entity/ViewCounter.php
  src/EventSubscriber/Entry/EntryShowSubscriber.php
  src/Factory/EntryFactory.php
  src/Repository/StatsRepository.php
  src/Repository/StatsViewsRepository.php
  src/Service/StatsManager.php
  symfony.lock
  templates/admin/_options.html.twig
  templates/entry/_info.html.twig
  templates/magazine/panel/_stats_pills.html.twig
  templates/stats/_options.html.twig
  templates/user/settings/_stats_pills.html.twig
  tests/Functional/Controller/Api/Entry/Admin/EntryChangeMagazineApiTest.php
  tests/Functional/Controller/Api/Entry/DomainEntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/EntryCreateApiTest.php
  tests/Functional/Controller/Api/Entry/EntryFavouriteApiTest.php
  tests/Functional/Controller/Api/Entry/EntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/EntryUpdateApiTest.php
  tests/Functional/Controller/Api/Entry/EntryVoteApiTest.php
  tests/Functional/Controller/Api/Entry/MagazineEntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/Moderate/EntryPinApiTest.php
  tests/Functional/Controller/Api/Entry/Moderate/EntrySetAdultApiTest.php
  tests/Functional/Controller/Api/Entry/Moderate/EntrySetLanguageApiTest.php
  tests/Functional/Controller/Api/Entry/Moderate/EntryTrashApiTest.php
  tests/Functional/Controller/Api/Entry/UserEntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Magazine/Admin/MagazineRetrieveStatsApiTest.php
  tests/WebTestCase.php
  translations/messages.en.yaml
Labels: dependencies, please review, needs feedback, backend

#676 add back magazine to post dto when in magazine view
  src/Controller/Entry/EntryFrontController.php
Labels: bug

#677 restrict login css to main content containers
  assets/styles/components/_login.scss
Labels: bug, low priority

#680 Fix circular ChainActivityMessage again again
  src/MessageHandler/ActivityPub/Inbox/AnnounceHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/DislikeHandler.php
  src/MessageHandler/ActivityPub/Inbox/LikeHandler.php
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#681 Fix some API calls
  src/Controller/Api/Domain/DomainRetrieveApi.php
  src/Controller/Api/Search/SearchRetrieveApi.php
  src/DTO/EntryResponseDto.php
  src/DTO/MagazineResponseDto.php
  src/Repository/UserRepository.php
Labels: bug, api

#682 Remove ratio from entry view
  templates/entry/_info.html.twig
  translations/messages.en.yaml
Labels: needs feedback

#679 Fix some bugs
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPubManager.php
  src/Service/MagazineManager.php
Labels: bug, activitypub, backend

#684 Adjust documentation for hosting
  C4.md
  CONTRIBUTING.md
  README.md
  docs/01-user/FAQ.md
  docs/01-user/README.md
  docs/01-user/user_guide.md
  docs/02-admin/01-installation/README.md
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/01-installation/docker.md
  docs/02-admin/02-configuration/README.md
  docs/02-admin/02-configuration/lets_encrypt.md
  docs/02-admin/02-configuration/mbin_config_files.md
  docs/02-admin/02-configuration/nginx.md
  docs/02-admin/03-optional-features/README.md
  docs/02-admin/03-optional-features/captcha.md
  docs/02-admin/03-optional-features/image_metadata_cleaning.md
  docs/02-admin/03-optional-features/mercure.md
  docs/02-admin/03-optional-features/s3_storage.md
  docs/02-admin/04-running-mbin/README.md
  docs/02-admin/04-running-mbin/backup.md
  docs/02-admin/04-running-mbin/first_setup.md
  docs/02-admin/04-running-mbin/messenger.md
  docs/02-admin/04-running-mbin/upgrades.md
  docs/02-admin/05-troubleshooting/README.md
  docs/02-admin/05-troubleshooting/bare_metal.md
  docs/02-admin/05-troubleshooting/docker.md
  docs/02-admin/99-tuning/README.md
  docs/02-admin/99-tuning/postgresql.md
  docs/02-admin/FAQ.md
  docs/02-admin/README.md
  docs/03-3rd_party_developer/README.md
  docs/03-3rd_party_developer/oauth2_guide.md
  docs/04-contributing/about-federation.md
  docs/04-contributing/developement_server.md
  docs/04-contributing/linting.md
  docs/README.md
  docs/admin_guide.md
Labels: documentation

#686 Remove logo preload when header logo disabled
  templates/base.html.twig
Labels: bug, low priority

#662 Upgrade to Symfony 7.x, package updates and removal of deprecated features
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/packages/scheb_2fa.yaml
  src/Entity/Client.php
  src/Security/KbinAuthenticator.php
  symfony.lock
Labels: dependencies, please review, backend

#693 Fix email route and add exception logging on failed emails
  src/Controller/ContactController.php
  templates/_email/email_base.html.twig
Labels: bug

#685 Admin and FAQ doc updates
  README.md
  docs/01-user/FAQ.md
  docs/02-admin/01-installation/bare_metal.md
  docs/02-admin/FAQ.md
  docs/03-3rd_party_developer/oauth2_guide.md
  docs/images/rabbit_reject_requeue_false.png
Labels: documentation

#699 switch magazine list to show magazine display names
  assets/styles/components/_magazine.scss
  templates/magazine/_list.html.twig
Labels: frontend

#701 Remove kbin migration, code bases are far too diverged to be a safe recommendation anymore
  README.md
Labels: documentation

#703 update magazine ban and log table foreign keys
  migrations/Version20240412010024.php
  src/Entity/MagazineBan.php
  src/Entity/MagazineLog.php
Labels: backend

#709 Small text changes to docs homepage
  docs/README.md
Labels: documentation

#664 initial eslint integration and ruleset config
  .eslintrc.json
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: enhancement, javascript

#714 Emphasize creating `random` magazine in first time install docs
  docs/02-admin/04-running-mbin/first_setup.md
Labels: documentation

#719 Replace nucleos/antispam-bundle with omines/antispam-bundle
  composer.json
  composer.lock
  config/bundles.php
  config/packages/antispam.yaml
  config/packages/nucleos_antispam.yaml
  config/packages/test/nucleos_antispam.yaml
  src/Controller/ContactController.php
  src/Controller/Security/RegisterController.php
  symfony.lock
Labels: enhancement, dependencies

#708 Add contributors to the README (automated)
  .github/workflows/contrib.yaml
  README.md
Labels: enhancement

#724 Update contributors readme
  README.md
Labels: enhancement

#648 Add page to view specific entry comments
  config/kbin_routes/entry.yaml
  src/Controller/Entry/Comment/EntryCommentViewController.php
  src/Service/Notification/EntryCommentNotificationManager.php
  src/Twig/Extension/UrlExtension.php
  src/Twig/Runtime/UrlExtensionRuntime.php
  templates/components/entry_comment.html.twig
  templates/entry/comment/_menu.html.twig
  templates/entry/comment/view.html.twig
  templates/layout/_subject_link.html.twig
  templates/modlog/_blocks.html.twig
  templates/notifications/_blocks.html.twig
Labels: enhancement

#678 feat: implement private mode
  config/packages/security.yaml
  config/services.yaml
  src/DTO/SettingsDto.php
  src/EventListener/FederationStatusListener.php
  src/Form/SettingsType.php
  src/Security/Voter/PrivateInstanceVoter.php
  src/Service/SettingsManager.php
  src/Twig/Extension/SettingsExtension.php
  src/Twig/Runtime/SettingsExtensionRuntime.php
  templates/admin/settings.html.twig
  templates/base.html.twig
  tests/Functional/Controller/Api/Instance/Admin/InstanceSettingsRetrieveApiTest.php
  tests/Functional/Controller/Api/Instance/Admin/InstanceSettingsUpdateApiTest.php
  translations/messages.en.yaml
Labels: enhancement, sso

#730 Update post-upgrade part 2
  bin/post-upgrade
Labels: enhancement

#694 Implement rules federation, fix markdown federation
  src/Factory/ActivityPub/GroupFactory.php
  src/Service/ActivityPubManager.php
Labels: bug, enhancement, activitypub, backend

#731 Faq vacuum messages
  docs/02-admin/FAQ.md
Labels: documentation

#737 post-upgrade detect env by reading `.env.local.php` directly
  bin/post-upgrade
Labels: enhancement

#736 Add page selector to user list at the top of the list users.html.twig
  templates/admin/users.html.twig
Labels: enhancement
