Repository MbinOrg/mbin, pull requests merged in 2025-03, with the labels that each got.

#1487 Extend public access roles for three API end-points
  config/packages/security.yaml
Labels: bug, backend

#1488 Explain how to use the bearer token now plus other minor improvements
  docs/04-app_developers/README.md
Labels: documentation, enhancement

#1486 Translations update from Hosted Weblate
  translations/messages.ru.yaml
Labels: translation

#1491 Update Symfony framework (patch release only)
  composer.lock
Labels: dependencies

#1492 Fix missing `Update` activity add cover and avatar removal
  src/Controller/Api/User/UserDeleteImagesApi.php
  src/Controller/User/Profile/UserEditController.php
  src/Controller/User/UserAvatarDeleteController.php
  src/Controller/User/UserCoverDeleteController.php
  src/MessageHandler/ActivityPub/Outbox/UpdateHandler.php
  src/Service/ActivityPubManager.php
  templates/user/settings/profile.html.twig
  translations/messages.en.yaml
Labels: bug, enhancement, frontend, activitypub, backend

#1472 Improve modlog (use showAvatars on all user_inline + possibility to hide new icon from modlog)
  src/Controller/User/ThemeSettingsController.php
  src/Markdown/CommonMark/ExternalLinkRenderer.php
  src/Twig/Components/MagazineInlineComponent.php
  src/Twig/Components/UserInlineComponent.php
  templates/admin/deletion_magazines.html.twig
  templates/admin/deletion_users.html.twig
  templates/admin/magazine_ownership.html.twig
  templates/admin/signup_requests.html.twig
  templates/admin/users.html.twig
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/entry_comment_inline_md.html.twig
  templates/components/entry_cross.html.twig
  templates/components/entry_inline_md.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/components/post_comment_inline_md.html.twig
  templates/components/post_inline_md.html.twig
  templates/components/related_magazines.html.twig
  templates/components/related_posts.html.twig
  templates/components/report_list.html.twig
  templates/components/user_inline.html.twig
  templates/layout/_options_appearance.html.twig
  templates/magazine/_list.html.twig
  templates/magazine/_moderators_sidebar.html.twig
  templates/magazine/list_abandoned.html.twig
  templates/magazine/panel/bans.html.twig
  templates/magazine/panel/moderator_requests.html.twig
  templates/messages/front.html.twig
  templates/messages/single.html.twig
  templates/modlog/_blocks.html.twig
  templates/modlog/front.html.twig
  templates/modlog/magazine.html.twig
  templates/notifications/_blocks.html.twig
  templates/user/_list.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#1500 Set the default from the default dto object in case of null
  src/DTO/UserSettingsDto.php
Labels: bug

#1494 Translations update from Hosted Weblate
  translations/messages.bg.yaml
  translations/messages.ca.yaml
  translations/messages.ca@valencia.yaml
  translations/messages.nl.yaml
Labels: translation

#1505 Add .vs directory to gitignore and dockerignore
  .dockerignore
  .gitignore
Labels: enhancement

#1514 Remove DMs and ban sender users command
  src/Command/RemoveDMAndBanCommand.php
Labels: enhancement, backend

#1515 Add documentation about the mbin:messages:remove_and_ban
  docs/02-admin/04-running-mbin/05-cli.md
Labels: documentation, enhancement

#1517 Docs: Extend pages for better findably and readability
  docs/02-admin/03-optional-features/04-user_application.md
  docs/02-admin/03-optional-features/05-image_metadata_cleaning.md
  docs/02-admin/03-optional-features/06-s3_storage.md
  docs/02-admin/03-optional-features/README.md
  docs/02-admin/03-optional-features/user_application.md
  docs/02-admin/05-troubleshooting/01-bare_metal.md
  docs/02-admin/05-troubleshooting/02-docker.md
  docs/02-admin/05-troubleshooting/README.md
  docs/02-admin/FAQ.md
  docs/02-admin/README.md
  docs/README.md
Labels: documentation, enhancement

#1518 Dump up to PHP v8.4
  docker/Dockerfile
Labels: enhancement, docker

#1519 Extend zz-docker with process manager config
  docker/php/php-fpm.d/zz-docker.conf
Labels: enhancement, docker

#1520 Docs: Upgrade to PHP v8.4. Explain min hw requirements. And other doc fixes
  docs/02-admin/01-installation/01-bare_metal.md
  docs/02-admin/01-installation/02-docker.md
  docs/02-admin/FAQ.md
  docs/03-contributing/01-getting_started.md
Labels: documentation, enhancement

#1525 Fix error during missing magazine parsing
  src/Markdown/Listener/CacheMarkdownListener.php
Labels: bug, backend

#1526 Inline all content previews
  assets/styles/components/_inline_md.scss
  src/Markdown/CommonMark/ExternalLinkRenderer.php
  src/Repository/ApActivityRepository.php
  templates/components/entry_comment_inline_md.html.twig
  templates/components/entry_inline_md.html.twig
  templates/components/post_comment_inline_md.html.twig
  templates/components/post_inline_md.html.twig
  tests/Unit/Utils/MarkdownTest.php
Labels: bug, frontend, backend

#1527 Update minor package versions
  composer.lock
Labels: dependencies

#1533 Fix period in remote usernames
  src/Service/MentionManager.php
Labels: enhancement
