Repository MbinOrg/mbin, pull requests merged in 2025-01, with the labels that each got.

#1341 PHPStan (+PHPUnit) corrections, pt 1
  .php-cs-fixer.dist.php
  src/ActivityPub/ActorHandle.php
  src/ActivityPub/JsonRd.php
  src/ActivityPub/JsonRdLink.php
  src/ArgumentValueResolver/FavouriteResolver.php
  src/ArgumentValueResolver/ReportResolver.php
  src/ArgumentValueResolver/VotableResolver.php
  src/Command/AwesomeBot/AwesomeBotEntries.php
  src/Command/AwesomeBot/AwesomeBotFixtures.php
  src/Command/AwesomeBot/AwesomeBotMagazine.php
  src/Command/MoveEntriesByTagCommand.php
  src/Command/MovePostsByTagCommand.php
  src/Command/RemoveDeadMessagesCommand.php
  src/Command/RemoveDuplicatesCommand.php
  src/Command/RemoveFailedMessagesCommand.php
  src/Command/Update/ApKeysUpdateCommand.php
  src/Command/Update/Async/ImageBlurhashHandler.php
  src/Command/Update/Async/NoteVisibilityHandler.php
  src/Command/Update/Async/NoteVisibilityMessage.php
  src/Command/Update/PostCommentRootUpdateCommand.php
  src/Command/Update/TagsUpdateCommand.php
  src/Command/Update/UserLastActiveUpdateCommand.php
  src/Controller/ActivityPub/NodeInfoController.php
  src/Controller/Admin/AdminDashboardController.php
  src/Controller/Admin/AdminFederationController.php
  src/Controller/Admin/AdminUsersController.php
  src/Controller/Api/BaseApi.php
  src/Controller/Api/Domain/DomainBaseApi.php
  src/Controller/Api/Entry/EntriesBaseApi.php
  src/DTO/MagazineLogResponseDto.php
  src/Message/ActivityPub/Inbox/ActivityMessage.php
  src/Repository/DomainRepository.php
  src/Repository/EntryCommentRepository.php
  src/Repository/EntryRepository.php
  src/Service/SearchManager.php
  tests/Unit/ActivityPub/ActorHandleTest.php
  tests/Unit/Service/ActivityPub/SignatureValidatorTest.php
  tests/Unit/Service/TagExtractorTest.php
  tests/Unit/Utils/SluggerTest.php
Labels: php, backend, DX

#1353 Upgraded to Symfony v7.2.* and upgraded other minor packages as well
  composer.json
  composer.lock
Labels: dependencies

#1362 Add testcase for hashtag matching
  .env.test
  src/Command/ApImportObject.php
  src/Controller/ActivityPub/WebFingerController.php
  src/Controller/SearchController.php
  src/Entity/User.php
  src/Event/ActivityPub/WebfingerResponseEvent.php
  src/EventSubscriber/ActivityPub/GroupWebFingerProfileSubscriber.php
  src/EventSubscriber/ActivityPub/GroupWebFingerSubscriber.php
  src/EventSubscriber/ActivityPub/UserWebFingerProfileSubscriber.php
  src/EventSubscriber/ActivityPub/UserWebFingerSubscriber.php
  src/Factory/ActivityPub/EntryCommentNoteFactory.php
  src/Factory/ActivityPub/EntryPageFactory.php
  src/Factory/ActivityPub/InstanceFactory.php
  src/Factory/ActivityPub/PostCommentNoteFactory.php
  src/Factory/ActivityPub/PostNoteFactory.php
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/AddHandler.php
  src/MessageHandler/ActivityPub/Inbox/ChainActivityHandler.php
  src/MessageHandler/ActivityPub/Inbox/FollowHandler.php
  src/MessageHandler/ActivityPub/Outbox/DeliverHandler.php
  src/MessageHandler/ActivityPub/Outbox/FollowHandler.php
  src/MessageHandler/ActivityPub/UpdateActorHandler.php
  src/Service/ActivityPub/ApHttpClient.php
  src/Service/ActivityPub/ApHttpClientInterface.php
  src/Service/ActivityPub/SignatureValidator.php
  src/Service/ActivityPub/Webfinger/WebFingerFactory.php
  src/Service/ActivityPubManager.php
  src/Service/EntryManager.php
  src/Service/PostManager.php
  src/Service/RemoteInstanceManager.php
  src/Service/SearchManager.php
  tests/FactoryTrait.php
  tests/Functional/Controller/Api/Search/SearchApiTest.php
  tests/TestingApHttpClient.php
  tests/Unit/ActivityPub/TagMatchTest.php
  tests/Unit/Service/ActivityPub/SignatureValidatorTest.php
  tests/WebTestCase.php
Labels: php, activitypub, testing

#1363 Upgraded Caddy image to v2.9.1
  docker/Dockerfile
Labels: enhancement

#1369 Fix generated markdown search link not prefilling the query field
  src/Markdown/CommonMark/MentionLinkParser.php
Labels: bug, backend

#1368 Fix search for URLs
  src/Controller/SearchController.php
Labels: bug, backend

#1355 Fix signup notifications for deleted accounts
  src/MessageHandler/Notification/SentNewSignupNotificationHandler.php
Labels: bug, backend

#1372 English sentence fixes
  translations/messages.en.yaml
Labels: translation

#1373 Fix checkmarks not being rendered correctly anymore, again
  assets/styles/layout/_forms.scss
Labels: bug, frontend

#1354 Mark signup notification as read automatically
  src/Controller/User/UserFrontController.php
  src/Repository/NotificationRepository.php
Labels: enhancement, backend

#1375 Fix Signup Notifications
  src/MessageHandler/Notification/SentNewSignupNotificationHandler.php
Labels: bug, backend

#1376 Move from dotenv to ini codeblocks
  docs/02-admin/02-configuration/02-nginx.md
  docs/02-admin/03-optional-features/02-sso.md
  docs/02-admin/03-optional-features/user_application.md
Labels: documentation

#1378 Translations update from Hosted Weblate
  translations/messages.gsw.yaml
Labels: translation

#1386 Ban additional Semrush agents
  public/robots.txt
Labels: enhancement

#1384 Translations update from Hosted Weblate
  translations/messages.zh_Hans.yaml
Labels: translation

#1387 Improve Nginx http accept regex
  docs/02-admin/02-configuration/02-nginx.md
Labels: bug, documentation, enhancement

#1383 Dump version in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#1377 Truncate body content in the production log
  src/MessageHandler/ActivityPub/Inbox/ActivityHandler.php
Labels: enhancement

#1346 Use Paratest in GitHub Action
  .github/workflows/action.yaml
  tests/Functional/Controller/Api/Domain/DomainBlockApiTest.php
  tests/Functional/Controller/Api/Entry/EntryUpdateApiTest.php
  tests/Functional/Controller/Api/Magazine/Admin/MagazineDeleteIconApiTest.php
  tests/Functional/Controller/Api/Magazine/Moderate/MagazineActionReportsApiTest.php
  tests/Functional/Controller/Api/OAuth2/OAuth2ClientApiTest.php
  tests/Functional/Controller/Api/Post/PostUpdateApiTest.php
  tests/Functional/Controller/Api/User/UserBlockApiTest.php
  tests/Functional/Controller/Api/User/UserFollowApiTest.php
  tests/Functional/Controller/Domain/DomainBlockControllerTest.php
  tests/Functional/Controller/Entry/Comment/EntryCommentCreateControllerTest.php
  tests/Functional/Controller/Entry/Comment/EntryCommentEditControllerTest.php
  tests/Functional/Controller/Entry/EntryCreateControllerTest.php
  tests/Functional/Controller/Entry/EntryEditControllerTest.php
  tests/Functional/Controller/Entry/EntryFrontControllerTest.php
  tests/Functional/Controller/Post/Comment/PostCommentCreateControllerTest.php
  tests/Functional/Controller/Post/Comment/PostCommentEditControllerTest.php
  tests/Functional/Controller/Post/PostCreateControllerTest.php
  tests/Functional/Controller/Post/PostEditControllerTest.php
  tests/Functional/Controller/Security/LoginControllerTest.php
  tests/Functional/Controller/User/Profile/UserEditControllerTest.php
  tests/Functional/Controller/User/UserBlockControllerTest.php
  tests/Functional/Controller/User/UserFollowControllerTest.php
  tests/WebTestCase.php
Labels: enhancement, testing, DX

#1272 [Feature] Custom notification settings
  assets/controllers/html_refresh_controller.js
  assets/controllers/subject_controller.js
  assets/styles/app.scss
  assets/styles/components/_entry.scss
  assets/styles/components/_magazine.scss
  assets/styles/components/_notification_switch.scss
  assets/styles/components/_popover.scss
  assets/styles/components/_post.scss
  assets/styles/components/_sidebar.scss
  assets/styles/components/_user.scss
  assets/styles/layout/_section.scss
  config/mbin_routes/notification_settings.yaml
  config/mbin_routes/notification_settings_api.yaml
  config/packages/doctrine.yaml
  migrations/Version20241125210454.php
  src/Controller/Api/BaseApi.php
  src/Controller/Api/Entry/EntriesBaseApi.php
  src/Controller/Api/Notification/NotificationSettingApi.php
  src/Controller/Api/Post/PostsBaseApi.php
  src/Controller/NotificationSettingsController.php
  src/DTO/EntryResponseDto.php
  src/DTO/MagazineResponseDto.php
  src/DTO/PostResponseDto.php
  src/DTO/UserResponseDto.php
  src/DoctrineExtensions/DBAL/Types/EnumNotificationStatus.php
  src/Entity/NotificationSettings.php
  src/Enums/ENotificationStatus.php
  src/Repository/NotificationSettingsRepository.php
  src/Service/Notification/EntryCommentNotificationManager.php
  src/Service/Notification/EntryNotificationManager.php
  src/Service/Notification/PostCommentNotificationManager.php
  src/Service/Notification/PostNotificationManager.php
  src/Twig/Components/NotificationSwitch.php
  src/Twig/Extension/FrontExtension.php
  src/Twig/Runtime/FrontExtensionRuntime.php
  templates/components/bookmark_list.html.twig
  templates/components/bookmark_standard.html.twig
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/magazine_box.html.twig
  templates/components/notification_switch.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/components/user_box.html.twig
  templates/entry/_info.html.twig
  templates/post/_info.html.twig
  templates/user/_user_popover.html.twig
  tests/WebTestCase.php
Labels: enhancement, frontend, backend

#1393 Fix flakiness of MagazineActionReportsApiTest::testApiCanAcceptReport
  tests/Functional/Controller/Api/Magazine/Moderate/MagazineActionReportsApiTest.php
Labels: bug, testing

#1396 Leverage GitHub Actons concurrency groups
  .github/workflows/action.yaml
  .github/workflows/psalm.yml
Labels: enhancement

#1394 Introducing the mbin:images:delete command
  docs/02-admin/04-running-mbin/05-cli.md
  src/Command/RemoveOldImagesCommand.php
Labels: enhancement, backend

#1366 Add twig component rendering to our markdown rendering
  assets/styles/app.scss
  assets/styles/components/_inline_md.scss
  src/Controller/User/ThemeSettingsController.php
  src/Markdown/CommonMark/ExternalLinkRenderer.php
  src/Markdown/CommonMark/MentionLinkParser.php
  src/Markdown/Event/BuildCacheContext.php
  src/Markdown/Event/ConvertMarkdown.php
  src/Markdown/Listener/CacheMarkdownListener.php
  src/MessageHandler/ActivityPub/Inbox/CreateHandler.php
  src/Repository/ApActivityRepository.php
  src/Service/MentionManager.php
  src/Twig/Components/EntryCommentInlineComponent.php
  src/Twig/Components/EntryInlineMdComponent.php
  src/Twig/Components/PostCommentInlineComponent.php
  src/Twig/Components/PostInlineMdComponent.php
  src/Twig/Components/UserInlineComponent.php
  src/Twig/Extension/UserExtension.php
  src/Twig/Runtime/UserExtensionRuntime.php
  src/Utils/UrlUtils.php
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/entry_comment_inline_md.html.twig
  templates/components/entry_cross.html.twig
  templates/components/entry_inline_md.html.twig
  templates/components/magazine_inline.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
  templates/components/post_comment_inline_md.html.twig
  templates/components/post_inline_md.html.twig
  templates/components/related_entries.html.twig
  templates/components/related_magazines.html.twig
  templates/components/related_posts.html.twig
  templates/components/user_inline.html.twig
  templates/layout/_magazine_activity_list.html.twig
  templates/layout/_options_appearance.html.twig
  templates/layout/_user_activity_list.html.twig
  templates/layout/sidebar_subscriptions.html.twig
  templates/magazine/_list.html.twig
  templates/user/_list.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#1402 Limit touch click detection to the content div
  assets/controllers/subject_controller.js
Labels: frontend, backend
