Repository MbinOrg/mbin, pull requests merged in 2025-04, with the labels that each got.

#1538 Fix SendApplicationAnswerMailHandler not supplying enough parameters
  src/MessageHandler/SendApplicationAnswerMailHandler.php
Labels: bug, backend, high priority

#1540 Docs: Update Docker nginx example with the existing nginx example
  docs/02-admin/01-installation/02-docker.md
Labels: documentation

#1547 Add cs2pr to our Dockerfile (phase 1)
  ci/Dockerfile
Labels: enhancement

#1546 Use checkstyle GitHub actions (phase 2)
  .github/workflows/action.yaml
Labels: enhancement

#1543 Fix warnings in logging + Update php-cs-fixer
  .github/workflows/action.yaml
  src/Markdown/Listener/CacheMarkdownListener.php
  src/Repository/ApActivityRepository.php
  src/Service/ActivityPub/Note.php
  src/Service/ActivityPub/SignatureValidator.php
  tools/composer.json
  tools/composer.lock
Labels: enhancement, activitypub, backend

#1560 Add missing $logger in ApActivityRepository + init $apActivity with null
  src/Markdown/CommonMark/ExternalLinkRenderer.php
  src/Repository/ApActivityRepository.php
Labels: bug, backend

#1542 Rework docker setup
  .devcontainer/.env.devcontainer
  .dockerignore
  .env.example
  .env.example_docker
  .gitignore
  compose.dev.yaml
  compose.yaml
  composer.json
  composer.lock
  config/packages/oneup_flysystem.yaml
  docker/.gitignore
  docker/Caddyfile
  docker/Dockerfile
  docker/caddy/Caddyfile
  docker/compose.prod.yml
  docker/compose.yml
  docker/conf.d/10-app.ini
  docker/conf.d/20-app.dev.ini
  docker/conf.d/20-app.prod.ini
  docker/docker-entrypoint
  docker/docker-entrypoint.sh
  docker/php/conf.d/app.ini
  docker/php/conf.d/app.prod.ini
  docker/php/php-fpm.d/zz-docker.conf
  docker/setup.sh
  docker/storage/.gitignore
  docker/tests/compose.yaml
  docker/tests/compose.yml
  docker/valkey.conf
  docs/02-admin/01-installation/01-bare_metal.md
  docs/02-admin/01-installation/02-docker.md
  docs/02-admin/01-installation/README.md
  docs/02-admin/02-configuration/01-mbin_config_files.md
  docs/02-admin/02-configuration/02-nginx.md
  docs/02-admin/03-optional-features/06-s3_storage.md
  docs/02-admin/04-running-mbin/01-first_setup.md
  docs/02-admin/04-running-mbin/02-backup.md
  docs/02-admin/04-running-mbin/03-upgrades.md
  docs/02-admin/05-troubleshooting/02-docker.md
  docs/02-admin/FAQ.md
  docs/02-admin/README.md
  docs/03-contributing/01-getting_started.md
  package-lock.json
Labels: enhancement, docker

#1550 Move complex regexes to dedicated regpatterns util
  src/Markdown/CommonMark/CommunityLinkParser.php
  src/Markdown/CommonMark/MentionLinkParser.php
  src/Markdown/Listener/CacheMarkdownListener.php
  src/Service/MentionManager.php
  src/Utils/RegPatterns.php
Labels: enhancement

#1565 Pin docker images to version tags
  docker/setup.sh
  docs/02-admin/01-installation/02-docker.md
Labels: documentation, enhancement, docker

#1566 Change leftover Redis reference to Valkey in Docker install docs
  docs/02-admin/01-installation/02-docker.md
Labels: documentation, docker

#1567 Left-over 'v' in front of our docker tags
  docker/setup.sh
  docs/02-admin/01-installation/02-docker.md
Labels: documentation

#1573 Check whether the actor is a User
  src/Service/ActivityPub/Note.php
Labels: bug, backend

#1563 Sort and filter comment replies the same as root comments
  src/Controller/Api/Entry/Comments/DomainEntryCommentsRetrieveApi.php
  src/Controller/Api/Entry/Comments/EntryCommentsRetrieveApi.php
  src/Controller/Api/Entry/Comments/EntryCommentsUpdateApi.php
  src/Controller/Api/Entry/Comments/UserEntryCommentsRetrieveApi.php
  src/Controller/Api/Entry/EntriesBaseApi.php
  src/Controller/Api/Post/Comments/PostCommentsRetrieveApi.php
  src/Controller/Api/Post/Comments/PostCommentsUpdateApi.php
  src/Controller/Api/Post/Comments/UserPostCommentsRetrieveApi.php
  src/Controller/Api/Post/PostsBaseApi.php
  src/Controller/Entry/Comment/EntryCommentViewController.php
  src/Controller/Entry/EntrySingleController.php
  src/Controller/Post/PostSingleController.php
  src/Controller/User/UserFrontController.php
  src/Entity/EntryComment.php
  src/Entity/PostComment.php
  src/Factory/EntryCommentFactory.php
  src/Factory/PostCommentFactory.php
  src/Repository/EntryCommentRepository.php
  src/Repository/PostCommentRepository.php
  src/Twig/Components/EntryCommentComponent.php
  src/Twig/Components/EntryCommentsNestedComponent.php
  src/Twig/Components/PostCommentComponent.php
  src/Twig/Components/PostCommentsNestedComponent.php
  src/Utils/ArrayUtils.php
  templates/components/entry_comment.html.twig
  templates/components/entry_comments_nested.html.twig
  templates/components/post_comment.html.twig
  templates/components/post_comments_nested.html.twig
  templates/entry/comment/_list.html.twig
  templates/entry/comment/view.html.twig
  templates/post/comment/_list.html.twig
Labels: enhancement, backend, api

#1578 WHen you enter a space during the search I was getting 500 error
  src/DTO/SearchDto.php
Labels: bug
