Repository MbinOrg/mbin, pull requests merged in 2025-02, with the labels that each got.

#1410 Add endpoint to create bookmark list
  config/mbin_routes/bookmark_api.yaml
  src/Controller/Api/Bookmark/BookmarkListApiController.php
Labels: enhancement, api

#1409 Fix NRE within the `ExternalLinkRenderer`
  src/Markdown/CommonMark/ExternalLinkRenderer.php
Labels: bug, backend

#1411 Fix signup notification links when approvals are enabled
  src/Controller/Admin/AdminSignupRequestsController.php
  src/Repository/UserRepository.php
  templates/admin/_options.html.twig
  templates/admin/signup_requests.html.twig
  templates/notifications/_blocks.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#1405 Fix nodeinfo not available when federation is disabled
  src/EventListener/FederationStatusListener.php
Labels: bug, backend, api

#1415 Fix notification api route methods
  config/mbin_routes/notification_api.yaml
  config/mbin_routes/notification_settings_api.yaml
Labels: api

#1403 Improve magazine matching in the `AddHandler`
  src/MessageHandler/ActivityPub/Inbox/AddHandler.php
Labels: bug, activitypub, backend

#1417 Update npm packages
  package-lock.json
  package.json
Labels: dependencies

#1416 Improve README (part 1 / x)
  README.md
Labels: documentation

#1426 Fix doctrine weirdness
  config/packages/doctrine.yaml
  migrations/Version20250204152300.php
Labels: bug, dependencies

#1433 Translations update from Hosted Weblate
  translations/messages.en.yaml
Labels: translation

#1430 Fix touch click on links in comments only opens comment
  assets/controllers/subject_controller.js
Labels: bug, frontend

#1425 Fix the bookmark API and add tests for it
  config/mbin_routes/bookmark_api.yaml
  config/packages/league_oauth2_server.yaml
  config/packages/security.yaml
  src/Controller/Api/Bookmark/BookmarkApiController.php
  src/Controller/Api/Bookmark/BookmarkListApiController.php
  src/DTO/BookmarksDto.php
  src/DTO/EntryCommentDto.php
  src/DTO/EntryCommentResponseDto.php
  src/DTO/EntryResponseDto.php
  src/DTO/OAuth2ClientDto.php
  src/DTO/PostCommentResponseDto.php
  src/DTO/PostResponseDto.php
  src/Entity/OAuth2UserConsent.php
  src/Factory/EntryCommentFactory.php
  src/Factory/EntryFactory.php
  src/Factory/PostCommentFactory.php
  src/Factory/PostFactory.php
  src/Repository/BookmarkListRepository.php
  src/Repository/BookmarkRepository.php
  tests/Functional/Controller/Api/Bookmark/BookmarkApiTest.php
  tests/Functional/Controller/Api/Bookmark/BookmarkListApiTest.php
  tests/Functional/Controller/Api/Entry/Comment/EntryCommentRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/EntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Post/Comment/PostCommentRetrieveApiTest.php
  tests/Functional/Controller/Api/Post/PostRetrieveApiTest.php
  tests/WebTestCase.php
  translations/messages.en.yaml
Labels: bug, backend, testing, api

#1437 Mark signup notification as read, after clicking on the link
  src/Controller/Admin/AdminSignupRequestsController.php
Labels: bug, enhancement

#1440 Adjust our pipeline docker file to use the prebuild ubuntu packages
  .github/workflows/build-and-publish-pipeline-image.yaml
  ci/Dockerfile
Labels: enhancement

#1441 Use new docker image
  .github/workflows/action.yaml
Labels: enhancement

#1420 Add missing cascade deletes to NotificationSettings
  migrations/Version20250203232039.php
  src/Entity/NotificationSettings.php
  tests/bootstrap.php
Labels: bug, backend

#1442 Update symfony packages + minor release
  .env.dev
  composer.lock
  config/packages/doctrine.yaml
  config/packages/framework.yaml
  symfony.lock
Labels: dependencies

#1445 Remove some cascade removes
  src/Entity/MessageThread.php
  src/Entity/NewSignupNotification.php
  src/Entity/NotificationSettings.php
  src/Entity/UserPushSubscription.php
Labels: bug, backend, high priority

#1446 Improve Markdown inline twig rendering
  src/Markdown/CommonMark/CommunityLinkParser.php
  src/Markdown/CommonMark/ExternalLinkRenderer.php
  src/Markdown/Listener/CacheMarkdownListener.php
  src/Service/ActivityPubManager.php
  src/Utils/UrlUtils.php
Labels: enhancement, frontend

#1448 Fix JS error with entries without short content
  assets/controllers/subject_controller.js
Labels: bug, frontend

#1447 Improve contrast of light themes (+ some dark theme fixes)
  assets/images/intro-bg-white.png
  assets/styles/components/_sidebar.scss
  assets/styles/components/_vote.scss
  assets/styles/layout/_layout.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-light.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
  assets/styles/themes/_kbin.scss
  assets/styles/themes/_tokyo-night.scss
Labels: enhancement, frontend

#1450 Fix the `NotificationSettingApi`
  config/packages/league_oauth2_server.yaml
  config/packages/security.yaml
  src/Controller/Api/BaseApi.php
  src/Controller/Api/Entry/EntriesBaseApi.php
  src/Controller/Api/Notification/NotificationSettingApi.php
  src/Controller/Api/Post/PostsBaseApi.php
  src/DTO/OAuth2ClientDto.php
  src/Entity/OAuth2UserConsent.php
  tests/Functional/Controller/Api/Notification/NotificationUpdateApiTest.php
Labels: bug, backend, api

#1453 Docs: Make vars unique in Nginx config
  docs/02-admin/02-configuration/02-nginx.md
Labels: documentation, enhancement

#1406 Always put thumb images in a lightbox
  assets/controllers/lightbox_controller.js
  assets/controllers/subject_controller.js
  templates/components/_figure_entry.html.twig
  templates/components/_figure_image.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
Labels: enhancement, frontend

#1455 Docs: Explictly enable JIT in PHP 8.4
  docs/02-admin/01-installation/01-bare_metal.md
Labels: documentation, enhancement

#1460 Some opcache and composer optimizations
  composer.json
  config/services.yaml
  docker/php/conf.d/app.prod.ini
  docs/02-admin/01-installation/01-bare_metal.md
Labels: documentation, enhancement, dependencies

#1461 Remove the `opcache.preload` setting for the docker build
  docker/php/conf.d/app.prod.ini
Labels: bug, docker

#1463 Revert .container.dumper.inline_factories
  config/services.yaml
Labels: bug

#1462 Create an appearance option: open lightbox for thumbnails
  src/Controller/User/ThemeSettingsController.php
  templates/components/_figure_entry.html.twig
  templates/layout/_options_appearance.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#1464 Translations update from Hosted Weblate
  translations/messages.en.yaml
Labels: translation

#1466 Move the thumbnail option to the Threads section
  templates/layout/_options_appearance.html.twig
Labels: enhancement, frontend

#1454 Render lemmy community links as preview
  src/Markdown/CommonMark/CommunityLinkParser.php
  src/Markdown/CommonMark/ExternalLinkRenderer.php
  src/Markdown/CommonMark/MentionLinkParser.php
  tests/Unit/Utils/MarkdownTest.php
  tests/WebTestCase.php
Labels: enhancement, frontend

#1468 Add all needed instructions for php install on debian 12
  docs/02-admin/01-installation/01-bare_metal.md
Labels: documentation

#1467 Enable option help + missing text for various options
  assets/styles/components/_settings_row.scss
  templates/components/_settings_row_enum.html.twig
  templates/components/_settings_row_switch.html.twig
  templates/layout/_options_appearance.html.twig
  translations/messages.en.yaml
Labels: bug, enhancement, accessibility

#1470 Docs: Remove dev setup from production guide + contribute improvements
  docs/02-admin/01-installation/01-bare_metal.md
  docs/03-contributing/01-getting_started.md
Labels: documentation, enhancement

#1473 Docs: Run docker compose from the project root dir
  docs/03-contributing/01-getting_started.md
Labels: documentation, enhancement

#1474 Also set MESSENGER_TRANSPORT_DSN in .env.test
  .env.test
Labels: enhancement, testing
