Repository MbinOrg/mbin, pull requests merged in 2025-05, with the labels that each got.

#1580 Improve SSO documentation for privacy portal
  docs/02-admin/03-optional-features/02-sso.md
Labels: documentation

#1576 Display the bookmark icon on trashed content
  templates/components/entry.html.twig
  templates/components/entry_comment.html.twig
  templates/components/post.html.twig
  templates/components/post_comment.html.twig
Labels: frontend

#1575 Display the 2FA secret upon setup
  assets/styles/components/_user.scss
  src/Controller/User/Profile/User2FAController.php
  templates/user/settings/2fa.html.twig
  templates/user/settings/2fa_secret.html.twig
  translations/messages.en.yaml
Labels: enhancement, frontend

#1577 Url Ids should not be extracted as a hashtag
  src/Markdown/Listener/CacheMarkdownListener.php
  src/Service/TagExtractor.php
  src/Utils/RegPatterns.php
  src/Utils/UrlUtils.php
  tests/Unit/Service/TagExtractorTest.php
Labels: bug, backend

#1588 Add emoji picker
  assets/controllers/markdown_toolbar_controller.js
  assets/styles/_variables.scss
  assets/styles/app.scss
  assets/styles/components/_emoji_picker.scss
  assets/styles/layout/_forms.scss
  assets/styles/mixins/theme-dark.scss
  assets/styles/mixins/theme-light.scss
  assets/styles/mixins/theme-solarized-dark.scss
  assets/styles/mixins/theme-solarized-light.scss
  assets/styles/themes/_kbin.scss
  assets/styles/themes/_tokyo-night.scss
  package-lock.json
  package.json
  templates/components/editor_toolbar.html.twig
  translations/messages.en.yaml
Labels: enhancement

#1599 Reduce the number of db calls on the login page
  templates/layout/_sidebar.html.twig
  templates/layout/_topbar.html.twig
Labels: bug, backend

#1618 Add `federation` query parameter to the post and entry retrieve API
  src/Controller/Api/Entry/EntriesRetrieveApi.php
  src/Controller/Api/Post/PostsRetrieveApi.php
  src/Repository/EntryRepository.php
  src/Repository/PostRepository.php
  tests/Functional/Controller/Api/Entry/EntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Post/PostRetrieveApiTest.php
Labels: enhancement, backend, api
