Repository MbinOrg/mbin, pull requests merged in 2025-09, with the labels that each got.

#1721 Update npm packages
  package-lock.json
Labels: dependencies

#1726 Increase memory limit to 512M (and slightly increase post_max_size)
  docs/02-admin/01-installation/01-bare_metal.md
Labels: documentation

#1731 Remove crosspost information from list API endpoints
  src/Controller/Api/Entry/DomainEntriesRetrieveApi.php
  src/Controller/Api/Entry/EntriesRetrieveApi.php
  src/Controller/Api/Entry/MagazineEntriesRetrieveApi.php
  src/Controller/Api/Entry/UserEntriesRetrieveApi.php
  src/DTO/EntryResponseDto.php
  tests/Functional/Controller/Api/Entry/DomainEntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/EntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/MagazineEntryRetrieveApiTest.php
  tests/Functional/Controller/Api/Entry/UserEntryRetrieveApiTest.php
Labels: api
