Repository MbinOrg/mbin, pull requests merged in 2025-07, with the labels that each got.

#1657 Expose instance admins and moderators
  config/mbin_routes/user_api.yaml
  config/packages/security.yaml
  src/Controller/Api/Instance/InstanceRetrieveInfoApi.php
  src/Controller/Api/User/UserRetrieveApi.php
  tests/FactoryTrait.php
  tests/Functional/Controller/Api/Instance/InstanceRetrieveInfoApiTest.php
  tests/Functional/Controller/Api/User/UserRetrieveApiTest.php
Labels: enhancement, backend, api

#1634 Improve admin user list
  assets/styles/components/_search.scss
  src/Controller/Admin/AdminUsersController.php
  src/Repository/UserRepository.php
  templates/admin/users.html.twig
Labels: enhancement, backend

#1635 Add Attitude to admin user list and user info
  src/Controller/Admin/AdminUsersController.php
  src/Repository/ReputationRepository.php
  src/Twig/Extension/UserExtension.php
  src/Twig/Runtime/UserExtensionRuntime.php
  templates/admin/users.html.twig
  templates/user/_info.html.twig
  translations/messages.en.yaml
Labels: enhancement, backend

#1665 Remove openssl error and deprecation
  src/Service/ActivityPub/ApHttpClient.php
Labels: enhancement, backend

#1669 Fix reading the wrong magazine property II
  src/Service/PostCommentManager.php
Labels: bug, backend

#1671 Add header bread crumb for mobile
  assets/styles/components/_header.scss
  templates/layout/_header.html.twig
Labels: enhancement, frontend

#1668 Rollback symfony packages to 7.2
  composer.json
  composer.lock
  package-lock.json
  symfony.lock
  tests/Functional/Controller/Api/Magazine/Admin/MagazineDeleteIconApiTest.php
  tests/Functional/Controller/Api/Magazine/Admin/MagazineUpdateThemeApiTest.php
  tests/Functional/Controller/Api/Search/SearchApiTest.php
  tests/Functional/Controller/Api/User/UserUpdateImagesApiTest.php
  tests/Functional/Controller/Entry/Comment/EntryCommentCreateControllerTest.php
  tests/Functional/Controller/Entry/EntryCreateControllerTest.php
  tests/Functional/Controller/Post/Comment/PostCommentCreateControllerTest.php
  tests/Functional/Controller/Post/PostCreateControllerTest.php
  tests/Functional/Controller/User/Profile/UserEditControllerTest.php
Labels: dependencies

#1679 Fix header crumb squashing on smaller devices
  assets/styles/components/_header.scss
Labels: bug, frontend

#1680 Fix header full width on desktop
  assets/styles/components/_header.scss
Labels: bug, frontend

#1682 Fix the if statement for $content variable in ApHttpClient.php
  src/Service/ActivityPub/ApHttpClient.php
Labels: enhancement, backend

#1686 Fix super slow search
  src/Repository/SearchRepository.php
Labels: enhancement, backend

#1684 Fix image and url edits not federating
  src/MessageHandler/ActivityPub/Inbox/UpdateHandler.php
  src/MessageHandler/AttachEntryEmbedHandler.php
  src/Service/ActivityPub/Page.php
  src/Service/ActivityPubManager.php
Labels: bug, activitypub, backend

#1685 Fix wrong usage of the `url` field in AP
  src/Factory/ActivityPub/EntryPageFactory.php
  tests/Unit/ActivityPub/Outbox/JsonSnapshots/AnnounceTest__testAnnounceCreateEntry__1.json
  tests/Unit/ActivityPub/Outbox/JsonSnapshots/AnnounceTest__testAnnounceUpdateEntry__1.json
  tests/Unit/ActivityPub/Outbox/JsonSnapshots/CreateTest__testCreateEntry__1.json
  tests/Unit/ActivityPub/Outbox/JsonSnapshots/UpdateTest__testUpdateEntry__1.json
Labels: bug, activitypub, backend

#1688 Bump version to v.1.8.3-rc1
  config/packages/framework.yaml
  src/Service/ProjectInfoService.php
Labels: backend
